// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"context"
	"fmt"
	"meshcart/kitex_gen/meshcart/base"
)

type OrderItemInput struct {
	ProductId int64 `thrift:"product_id,1" frugal:"1,default,i64" json:"product_id"`
	SkuId     int64 `thrift:"sku_id,2" frugal:"2,default,i64" json:"sku_id"`
	Quantity  int32 `thrift:"quantity,3" frugal:"3,default,i32" json:"quantity"`
}

func NewOrderItemInput() *OrderItemInput {
	return &OrderItemInput{}
}

func (p *OrderItemInput) InitDefault() {
}

func (p *OrderItemInput) GetProductId() (v int64) {
	return p.ProductId
}

func (p *OrderItemInput) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *OrderItemInput) GetQuantity() (v int32) {
	return p.Quantity
}
func (p *OrderItemInput) SetProductId(val int64) {
	p.ProductId = val
}
func (p *OrderItemInput) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *OrderItemInput) SetQuantity(val int32) {
	p.Quantity = val
}

func (p *OrderItemInput) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderItemInput(%+v)", *p)
}

var fieldIDToName_OrderItemInput = map[int16]string{
	1: "product_id",
	2: "sku_id",
	3: "quantity",
}

type OrderItem struct {
	ItemId               int64  `thrift:"item_id,1" frugal:"1,default,i64" json:"item_id"`
	OrderId              int64  `thrift:"order_id,2" frugal:"2,default,i64" json:"order_id"`
	ProductId            int64  `thrift:"product_id,3" frugal:"3,default,i64" json:"product_id"`
	SkuId                int64  `thrift:"sku_id,4" frugal:"4,default,i64" json:"sku_id"`
	ProductTitleSnapshot string `thrift:"product_title_snapshot,5" frugal:"5,default,string" json:"product_title_snapshot"`
	SkuTitleSnapshot     string `thrift:"sku_title_snapshot,6" frugal:"6,default,string" json:"sku_title_snapshot"`
	SalePriceSnapshot    int64  `thrift:"sale_price_snapshot,7" frugal:"7,default,i64" json:"sale_price_snapshot"`
	Quantity             int32  `thrift:"quantity,8" frugal:"8,default,i32" json:"quantity"`
	SubtotalAmount       int64  `thrift:"subtotal_amount,9" frugal:"9,default,i64" json:"subtotal_amount"`
}

func NewOrderItem() *OrderItem {
	return &OrderItem{}
}

func (p *OrderItem) InitDefault() {
}

func (p *OrderItem) GetItemId() (v int64) {
	return p.ItemId
}

func (p *OrderItem) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *OrderItem) GetProductId() (v int64) {
	return p.ProductId
}

func (p *OrderItem) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *OrderItem) GetProductTitleSnapshot() (v string) {
	return p.ProductTitleSnapshot
}

func (p *OrderItem) GetSkuTitleSnapshot() (v string) {
	return p.SkuTitleSnapshot
}

func (p *OrderItem) GetSalePriceSnapshot() (v int64) {
	return p.SalePriceSnapshot
}

func (p *OrderItem) GetQuantity() (v int32) {
	return p.Quantity
}

func (p *OrderItem) GetSubtotalAmount() (v int64) {
	return p.SubtotalAmount
}
func (p *OrderItem) SetItemId(val int64) {
	p.ItemId = val
}
func (p *OrderItem) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *OrderItem) SetProductId(val int64) {
	p.ProductId = val
}
func (p *OrderItem) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *OrderItem) SetProductTitleSnapshot(val string) {
	p.ProductTitleSnapshot = val
}
func (p *OrderItem) SetSkuTitleSnapshot(val string) {
	p.SkuTitleSnapshot = val
}
func (p *OrderItem) SetSalePriceSnapshot(val int64) {
	p.SalePriceSnapshot = val
}
func (p *OrderItem) SetQuantity(val int32) {
	p.Quantity = val
}
func (p *OrderItem) SetSubtotalAmount(val int64) {
	p.SubtotalAmount = val
}

func (p *OrderItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderItem(%+v)", *p)
}

var fieldIDToName_OrderItem = map[int16]string{
	1: "item_id",
	2: "order_id",
	3: "product_id",
	4: "sku_id",
	5: "product_title_snapshot",
	6: "sku_title_snapshot",
	7: "sale_price_snapshot",
	8: "quantity",
	9: "subtotal_amount",
}

type Order struct {
	OrderId        int64        `thrift:"order_id,1" frugal:"1,default,i64" json:"order_id"`
	UserId         int64        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	Status         int32        `thrift:"status,3" frugal:"3,default,i32" json:"status"`
	TotalAmount    int64        `thrift:"total_amount,4" frugal:"4,default,i64" json:"total_amount"`
	PayAmount      int64        `thrift:"pay_amount,5" frugal:"5,default,i64" json:"pay_amount"`
	ExpireAt       int64        `thrift:"expire_at,6" frugal:"6,default,i64" json:"expire_at"`
	Items          []*OrderItem `thrift:"items,7" frugal:"7,default,list<OrderItem>" json:"items"`
	CancelReason   string       `thrift:"cancel_reason,8" frugal:"8,default,string" json:"cancel_reason"`
	PaymentId      string       `thrift:"payment_id,9" frugal:"9,default,string" json:"payment_id"`
	PaidAt         int64        `thrift:"paid_at,10" frugal:"10,default,i64" json:"paid_at"`
	PaymentMethod  string       `thrift:"payment_method,11" frugal:"11,default,string" json:"payment_method"`
	PaymentTradeNo string       `thrift:"payment_trade_no,12" frugal:"12,default,string" json:"payment_trade_no"`
}

func NewOrder() *Order {
	return &Order{}
}

func (p *Order) InitDefault() {
}

func (p *Order) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *Order) GetUserId() (v int64) {
	return p.UserId
}

func (p *Order) GetStatus() (v int32) {
	return p.Status
}

func (p *Order) GetTotalAmount() (v int64) {
	return p.TotalAmount
}

func (p *Order) GetPayAmount() (v int64) {
	return p.PayAmount
}

func (p *Order) GetExpireAt() (v int64) {
	return p.ExpireAt
}

func (p *Order) GetItems() (v []*OrderItem) {
	return p.Items
}

func (p *Order) GetCancelReason() (v string) {
	return p.CancelReason
}

func (p *Order) GetPaymentId() (v string) {
	return p.PaymentId
}

func (p *Order) GetPaidAt() (v int64) {
	return p.PaidAt
}

func (p *Order) GetPaymentMethod() (v string) {
	return p.PaymentMethod
}

func (p *Order) GetPaymentTradeNo() (v string) {
	return p.PaymentTradeNo
}
func (p *Order) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *Order) SetUserId(val int64) {
	p.UserId = val
}
func (p *Order) SetStatus(val int32) {
	p.Status = val
}
func (p *Order) SetTotalAmount(val int64) {
	p.TotalAmount = val
}
func (p *Order) SetPayAmount(val int64) {
	p.PayAmount = val
}
func (p *Order) SetExpireAt(val int64) {
	p.ExpireAt = val
}
func (p *Order) SetItems(val []*OrderItem) {
	p.Items = val
}
func (p *Order) SetCancelReason(val string) {
	p.CancelReason = val
}
func (p *Order) SetPaymentId(val string) {
	p.PaymentId = val
}
func (p *Order) SetPaidAt(val int64) {
	p.PaidAt = val
}
func (p *Order) SetPaymentMethod(val string) {
	p.PaymentMethod = val
}
func (p *Order) SetPaymentTradeNo(val string) {
	p.PaymentTradeNo = val
}

func (p *Order) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Order(%+v)", *p)
}

var fieldIDToName_Order = map[int16]string{
	1:  "order_id",
	2:  "user_id",
	3:  "status",
	4:  "total_amount",
	5:  "pay_amount",
	6:  "expire_at",
	7:  "items",
	8:  "cancel_reason",
	9:  "payment_id",
	10: "paid_at",
	11: "payment_method",
	12: "payment_trade_no",
}

type CreateOrderRequest struct {
	UserId    int64             `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Items     []*OrderItemInput `thrift:"items,2" frugal:"2,default,list<OrderItemInput>" json:"items"`
	RequestId *string           `thrift:"request_id,3,optional" frugal:"3,optional,string" json:"request_id,omitempty"`
}

func NewCreateOrderRequest() *CreateOrderRequest {
	return &CreateOrderRequest{}
}

func (p *CreateOrderRequest) InitDefault() {
}

func (p *CreateOrderRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateOrderRequest) GetItems() (v []*OrderItemInput) {
	return p.Items
}

var CreateOrderRequest_RequestId_DEFAULT string

func (p *CreateOrderRequest) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return CreateOrderRequest_RequestId_DEFAULT
	}
	return *p.RequestId
}
func (p *CreateOrderRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateOrderRequest) SetItems(val []*OrderItemInput) {
	p.Items = val
}
func (p *CreateOrderRequest) SetRequestId(val *string) {
	p.RequestId = val
}

func (p *CreateOrderRequest) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *CreateOrderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderRequest(%+v)", *p)
}

var fieldIDToName_CreateOrderRequest = map[int16]string{
	1: "user_id",
	2: "items",
	3: "request_id",
}

type CreateOrderResponse struct {
	Order *Order             `thrift:"order,1" frugal:"1,default,Order" json:"order"`
	Base  *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewCreateOrderResponse() *CreateOrderResponse {
	return &CreateOrderResponse{}
}

func (p *CreateOrderResponse) InitDefault() {
}

var CreateOrderResponse_Order_DEFAULT *Order

func (p *CreateOrderResponse) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return CreateOrderResponse_Order_DEFAULT
	}
	return p.Order
}

var CreateOrderResponse_Base_DEFAULT *base.BaseResponse

func (p *CreateOrderResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return CreateOrderResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *CreateOrderResponse) SetOrder(val *Order) {
	p.Order = val
}
func (p *CreateOrderResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *CreateOrderResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *CreateOrderResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateOrderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResponse(%+v)", *p)
}

var fieldIDToName_CreateOrderResponse = map[int16]string{
	1:   "order",
	255: "base",
}

type CancelOrderRequest struct {
	UserId       int64   `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	OrderId      int64   `thrift:"order_id,2" frugal:"2,default,i64" json:"order_id"`
	CancelReason *string `thrift:"cancel_reason,3,optional" frugal:"3,optional,string" json:"cancel_reason,omitempty"`
	RequestId    *string `thrift:"request_id,4,optional" frugal:"4,optional,string" json:"request_id,omitempty"`
}

func NewCancelOrderRequest() *CancelOrderRequest {
	return &CancelOrderRequest{}
}

func (p *CancelOrderRequest) InitDefault() {
}

func (p *CancelOrderRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CancelOrderRequest) GetOrderId() (v int64) {
	return p.OrderId
}

var CancelOrderRequest_CancelReason_DEFAULT string

func (p *CancelOrderRequest) GetCancelReason() (v string) {
	if !p.IsSetCancelReason() {
		return CancelOrderRequest_CancelReason_DEFAULT
	}
	return *p.CancelReason
}

var CancelOrderRequest_RequestId_DEFAULT string

func (p *CancelOrderRequest) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return CancelOrderRequest_RequestId_DEFAULT
	}
	return *p.RequestId
}
func (p *CancelOrderRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CancelOrderRequest) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *CancelOrderRequest) SetCancelReason(val *string) {
	p.CancelReason = val
}
func (p *CancelOrderRequest) SetRequestId(val *string) {
	p.RequestId = val
}

func (p *CancelOrderRequest) IsSetCancelReason() bool {
	return p.CancelReason != nil
}

func (p *CancelOrderRequest) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *CancelOrderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderRequest(%+v)", *p)
}

var fieldIDToName_CancelOrderRequest = map[int16]string{
	1: "user_id",
	2: "order_id",
	3: "cancel_reason",
	4: "request_id",
}

type CancelOrderResponse struct {
	Order *Order             `thrift:"order,1" frugal:"1,default,Order" json:"order"`
	Base  *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewCancelOrderResponse() *CancelOrderResponse {
	return &CancelOrderResponse{}
}

func (p *CancelOrderResponse) InitDefault() {
}

var CancelOrderResponse_Order_DEFAULT *Order

func (p *CancelOrderResponse) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return CancelOrderResponse_Order_DEFAULT
	}
	return p.Order
}

var CancelOrderResponse_Base_DEFAULT *base.BaseResponse

func (p *CancelOrderResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return CancelOrderResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *CancelOrderResponse) SetOrder(val *Order) {
	p.Order = val
}
func (p *CancelOrderResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *CancelOrderResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *CancelOrderResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *CancelOrderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderResponse(%+v)", *p)
}

var fieldIDToName_CancelOrderResponse = map[int16]string{
	1:   "order",
	255: "base",
}

type ConfirmOrderPaidRequest struct {
	OrderId        int64   `thrift:"order_id,1" frugal:"1,default,i64" json:"order_id"`
	PaymentId      string  `thrift:"payment_id,2" frugal:"2,default,string" json:"payment_id"`
	RequestId      *string `thrift:"request_id,3,optional" frugal:"3,optional,string" json:"request_id,omitempty"`
	PaymentMethod  *string `thrift:"payment_method,4,optional" frugal:"4,optional,string" json:"payment_method,omitempty"`
	PaymentTradeNo *string `thrift:"payment_trade_no,5,optional" frugal:"5,optional,string" json:"payment_trade_no,omitempty"`
	PaidAt         *int64  `thrift:"paid_at,6,optional" frugal:"6,optional,i64" json:"paid_at,omitempty"`
}

func NewConfirmOrderPaidRequest() *ConfirmOrderPaidRequest {
	return &ConfirmOrderPaidRequest{}
}

func (p *ConfirmOrderPaidRequest) InitDefault() {
}

func (p *ConfirmOrderPaidRequest) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *ConfirmOrderPaidRequest) GetPaymentId() (v string) {
	return p.PaymentId
}

var ConfirmOrderPaidRequest_RequestId_DEFAULT string

func (p *ConfirmOrderPaidRequest) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return ConfirmOrderPaidRequest_RequestId_DEFAULT
	}
	return *p.RequestId
}

var ConfirmOrderPaidRequest_PaymentMethod_DEFAULT string

func (p *ConfirmOrderPaidRequest) GetPaymentMethod() (v string) {
	if !p.IsSetPaymentMethod() {
		return ConfirmOrderPaidRequest_PaymentMethod_DEFAULT
	}
	return *p.PaymentMethod
}

var ConfirmOrderPaidRequest_PaymentTradeNo_DEFAULT string

func (p *ConfirmOrderPaidRequest) GetPaymentTradeNo() (v string) {
	if !p.IsSetPaymentTradeNo() {
		return ConfirmOrderPaidRequest_PaymentTradeNo_DEFAULT
	}
	return *p.PaymentTradeNo
}

var ConfirmOrderPaidRequest_PaidAt_DEFAULT int64

func (p *ConfirmOrderPaidRequest) GetPaidAt() (v int64) {
	if !p.IsSetPaidAt() {
		return ConfirmOrderPaidRequest_PaidAt_DEFAULT
	}
	return *p.PaidAt
}
func (p *ConfirmOrderPaidRequest) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *ConfirmOrderPaidRequest) SetPaymentId(val string) {
	p.PaymentId = val
}
func (p *ConfirmOrderPaidRequest) SetRequestId(val *string) {
	p.RequestId = val
}
func (p *ConfirmOrderPaidRequest) SetPaymentMethod(val *string) {
	p.PaymentMethod = val
}
func (p *ConfirmOrderPaidRequest) SetPaymentTradeNo(val *string) {
	p.PaymentTradeNo = val
}
func (p *ConfirmOrderPaidRequest) SetPaidAt(val *int64) {
	p.PaidAt = val
}

func (p *ConfirmOrderPaidRequest) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *ConfirmOrderPaidRequest) IsSetPaymentMethod() bool {
	return p.PaymentMethod != nil
}

func (p *ConfirmOrderPaidRequest) IsSetPaymentTradeNo() bool {
	return p.PaymentTradeNo != nil
}

func (p *ConfirmOrderPaidRequest) IsSetPaidAt() bool {
	return p.PaidAt != nil
}

func (p *ConfirmOrderPaidRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmOrderPaidRequest(%+v)", *p)
}

var fieldIDToName_ConfirmOrderPaidRequest = map[int16]string{
	1: "order_id",
	2: "payment_id",
	3: "request_id",
	4: "payment_method",
	5: "payment_trade_no",
	6: "paid_at",
}

type ConfirmOrderPaidResponse struct {
	Order *Order             `thrift:"order,1" frugal:"1,default,Order" json:"order"`
	Base  *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewConfirmOrderPaidResponse() *ConfirmOrderPaidResponse {
	return &ConfirmOrderPaidResponse{}
}

func (p *ConfirmOrderPaidResponse) InitDefault() {
}

var ConfirmOrderPaidResponse_Order_DEFAULT *Order

func (p *ConfirmOrderPaidResponse) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return ConfirmOrderPaidResponse_Order_DEFAULT
	}
	return p.Order
}

var ConfirmOrderPaidResponse_Base_DEFAULT *base.BaseResponse

func (p *ConfirmOrderPaidResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return ConfirmOrderPaidResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *ConfirmOrderPaidResponse) SetOrder(val *Order) {
	p.Order = val
}
func (p *ConfirmOrderPaidResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *ConfirmOrderPaidResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *ConfirmOrderPaidResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *ConfirmOrderPaidResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmOrderPaidResponse(%+v)", *p)
}

var fieldIDToName_ConfirmOrderPaidResponse = map[int16]string{
	1:   "order",
	255: "base",
}

type GetOrderRequest struct {
	UserId  int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	OrderId int64 `thrift:"order_id,2" frugal:"2,default,i64" json:"order_id"`
}

func NewGetOrderRequest() *GetOrderRequest {
	return &GetOrderRequest{}
}

func (p *GetOrderRequest) InitDefault() {
}

func (p *GetOrderRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetOrderRequest) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *GetOrderRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetOrderRequest) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *GetOrderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderRequest(%+v)", *p)
}

var fieldIDToName_GetOrderRequest = map[int16]string{
	1: "user_id",
	2: "order_id",
}

type GetOrderResponse struct {
	Order *Order             `thrift:"order,1" frugal:"1,default,Order" json:"order"`
	Base  *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewGetOrderResponse() *GetOrderResponse {
	return &GetOrderResponse{}
}

func (p *GetOrderResponse) InitDefault() {
}

var GetOrderResponse_Order_DEFAULT *Order

func (p *GetOrderResponse) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return GetOrderResponse_Order_DEFAULT
	}
	return p.Order
}

var GetOrderResponse_Base_DEFAULT *base.BaseResponse

func (p *GetOrderResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return GetOrderResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *GetOrderResponse) SetOrder(val *Order) {
	p.Order = val
}
func (p *GetOrderResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *GetOrderResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *GetOrderResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetOrderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderResponse(%+v)", *p)
}

var fieldIDToName_GetOrderResponse = map[int16]string{
	1:   "order",
	255: "base",
}

type ListOrdersRequest struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Page     int32 `thrift:"page,2" frugal:"2,default,i32" json:"page"`
	PageSize int32 `thrift:"page_size,3" frugal:"3,default,i32" json:"page_size"`
}

func NewListOrdersRequest() *ListOrdersRequest {
	return &ListOrdersRequest{}
}

func (p *ListOrdersRequest) InitDefault() {
}

func (p *ListOrdersRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *ListOrdersRequest) GetPage() (v int32) {
	return p.Page
}

func (p *ListOrdersRequest) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *ListOrdersRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *ListOrdersRequest) SetPage(val int32) {
	p.Page = val
}
func (p *ListOrdersRequest) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *ListOrdersRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersRequest(%+v)", *p)
}

var fieldIDToName_ListOrdersRequest = map[int16]string{
	1: "user_id",
	2: "page",
	3: "page_size",
}

type ListOrdersResponse struct {
	Orders []*Order           `thrift:"orders,1" frugal:"1,default,list<Order>" json:"orders"`
	Total  int64              `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	Base   *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewListOrdersResponse() *ListOrdersResponse {
	return &ListOrdersResponse{}
}

func (p *ListOrdersResponse) InitDefault() {
}

func (p *ListOrdersResponse) GetOrders() (v []*Order) {
	return p.Orders
}

func (p *ListOrdersResponse) GetTotal() (v int64) {
	return p.Total
}

var ListOrdersResponse_Base_DEFAULT *base.BaseResponse

func (p *ListOrdersResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return ListOrdersResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *ListOrdersResponse) SetOrders(val []*Order) {
	p.Orders = val
}
func (p *ListOrdersResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *ListOrdersResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *ListOrdersResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListOrdersResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersResponse(%+v)", *p)
}

var fieldIDToName_ListOrdersResponse = map[int16]string{
	1:   "orders",
	2:   "total",
	255: "base",
}

type CloseExpiredOrdersRequest struct {
	Limit *int32 `thrift:"limit,1,optional" frugal:"1,optional,i32" json:"limit,omitempty"`
}

func NewCloseExpiredOrdersRequest() *CloseExpiredOrdersRequest {
	return &CloseExpiredOrdersRequest{}
}

func (p *CloseExpiredOrdersRequest) InitDefault() {
}

var CloseExpiredOrdersRequest_Limit_DEFAULT int32

func (p *CloseExpiredOrdersRequest) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return CloseExpiredOrdersRequest_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *CloseExpiredOrdersRequest) SetLimit(val *int32) {
	p.Limit = val
}

func (p *CloseExpiredOrdersRequest) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *CloseExpiredOrdersRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloseExpiredOrdersRequest(%+v)", *p)
}

var fieldIDToName_CloseExpiredOrdersRequest = map[int16]string{
	1: "limit",
}

type CloseExpiredOrdersResponse struct {
	ClosedCount int32              `thrift:"closed_count,1" frugal:"1,default,i32" json:"closed_count"`
	OrderIds    []int64            `thrift:"order_ids,2" frugal:"2,default,list<i64>" json:"order_ids"`
	Base        *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewCloseExpiredOrdersResponse() *CloseExpiredOrdersResponse {
	return &CloseExpiredOrdersResponse{}
}

func (p *CloseExpiredOrdersResponse) InitDefault() {
}

func (p *CloseExpiredOrdersResponse) GetClosedCount() (v int32) {
	return p.ClosedCount
}

func (p *CloseExpiredOrdersResponse) GetOrderIds() (v []int64) {
	return p.OrderIds
}

var CloseExpiredOrdersResponse_Base_DEFAULT *base.BaseResponse

func (p *CloseExpiredOrdersResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return CloseExpiredOrdersResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *CloseExpiredOrdersResponse) SetClosedCount(val int32) {
	p.ClosedCount = val
}
func (p *CloseExpiredOrdersResponse) SetOrderIds(val []int64) {
	p.OrderIds = val
}
func (p *CloseExpiredOrdersResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *CloseExpiredOrdersResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *CloseExpiredOrdersResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloseExpiredOrdersResponse(%+v)", *p)
}

var fieldIDToName_CloseExpiredOrdersResponse = map[int16]string{
	1:   "closed_count",
	2:   "order_ids",
	255: "base",
}

type OrderService interface {
	CreateOrder(ctx context.Context, request *CreateOrderRequest) (r *CreateOrderResponse, err error)

	CancelOrder(ctx context.Context, request *CancelOrderRequest) (r *CancelOrderResponse, err error)

	ConfirmOrderPaid(ctx context.Context, request *ConfirmOrderPaidRequest) (r *ConfirmOrderPaidResponse, err error)

	GetOrder(ctx context.Context, request *GetOrderRequest) (r *GetOrderResponse, err error)

	ListOrders(ctx context.Context, request *ListOrdersRequest) (r *ListOrdersResponse, err error)

	CloseExpiredOrders(ctx context.Context, request *CloseExpiredOrdersRequest) (r *CloseExpiredOrdersResponse, err error)
}

type OrderServiceCreateOrderArgs struct {
	Request *CreateOrderRequest `thrift:"request,1" frugal:"1,default,CreateOrderRequest" json:"request"`
}

func NewOrderServiceCreateOrderArgs() *OrderServiceCreateOrderArgs {
	return &OrderServiceCreateOrderArgs{}
}

func (p *OrderServiceCreateOrderArgs) InitDefault() {
}

var OrderServiceCreateOrderArgs_Request_DEFAULT *CreateOrderRequest

func (p *OrderServiceCreateOrderArgs) GetRequest() (v *CreateOrderRequest) {
	if !p.IsSetRequest() {
		return OrderServiceCreateOrderArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OrderServiceCreateOrderArgs) SetRequest(val *CreateOrderRequest) {
	p.Request = val
}

func (p *OrderServiceCreateOrderArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OrderServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderArgs = map[int16]string{
	1: "request",
}

type OrderServiceCreateOrderResult struct {
	Success *CreateOrderResponse `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResponse" json:"success,omitempty"`
}

func NewOrderServiceCreateOrderResult() *OrderServiceCreateOrderResult {
	return &OrderServiceCreateOrderResult{}
}

func (p *OrderServiceCreateOrderResult) InitDefault() {
}

var OrderServiceCreateOrderResult_Success_DEFAULT *CreateOrderResponse

func (p *OrderServiceCreateOrderResult) GetSuccess() (v *CreateOrderResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResponse)
}

func (p *OrderServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceCancelOrderArgs struct {
	Request *CancelOrderRequest `thrift:"request,1" frugal:"1,default,CancelOrderRequest" json:"request"`
}

func NewOrderServiceCancelOrderArgs() *OrderServiceCancelOrderArgs {
	return &OrderServiceCancelOrderArgs{}
}

func (p *OrderServiceCancelOrderArgs) InitDefault() {
}

var OrderServiceCancelOrderArgs_Request_DEFAULT *CancelOrderRequest

func (p *OrderServiceCancelOrderArgs) GetRequest() (v *CancelOrderRequest) {
	if !p.IsSetRequest() {
		return OrderServiceCancelOrderArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OrderServiceCancelOrderArgs) SetRequest(val *CancelOrderRequest) {
	p.Request = val
}

func (p *OrderServiceCancelOrderArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OrderServiceCancelOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCancelOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCancelOrderArgs = map[int16]string{
	1: "request",
}

type OrderServiceCancelOrderResult struct {
	Success *CancelOrderResponse `thrift:"success,0,optional" frugal:"0,optional,CancelOrderResponse" json:"success,omitempty"`
}

func NewOrderServiceCancelOrderResult() *OrderServiceCancelOrderResult {
	return &OrderServiceCancelOrderResult{}
}

func (p *OrderServiceCancelOrderResult) InitDefault() {
}

var OrderServiceCancelOrderResult_Success_DEFAULT *CancelOrderResponse

func (p *OrderServiceCancelOrderResult) GetSuccess() (v *CancelOrderResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceCancelOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCancelOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CancelOrderResponse)
}

func (p *OrderServiceCancelOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCancelOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCancelOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCancelOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceConfirmOrderPaidArgs struct {
	Request *ConfirmOrderPaidRequest `thrift:"request,1" frugal:"1,default,ConfirmOrderPaidRequest" json:"request"`
}

func NewOrderServiceConfirmOrderPaidArgs() *OrderServiceConfirmOrderPaidArgs {
	return &OrderServiceConfirmOrderPaidArgs{}
}

func (p *OrderServiceConfirmOrderPaidArgs) InitDefault() {
}

var OrderServiceConfirmOrderPaidArgs_Request_DEFAULT *ConfirmOrderPaidRequest

func (p *OrderServiceConfirmOrderPaidArgs) GetRequest() (v *ConfirmOrderPaidRequest) {
	if !p.IsSetRequest() {
		return OrderServiceConfirmOrderPaidArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OrderServiceConfirmOrderPaidArgs) SetRequest(val *ConfirmOrderPaidRequest) {
	p.Request = val
}

func (p *OrderServiceConfirmOrderPaidArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OrderServiceConfirmOrderPaidArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceConfirmOrderPaidArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceConfirmOrderPaidArgs = map[int16]string{
	1: "request",
}

type OrderServiceConfirmOrderPaidResult struct {
	Success *ConfirmOrderPaidResponse `thrift:"success,0,optional" frugal:"0,optional,ConfirmOrderPaidResponse" json:"success,omitempty"`
}

func NewOrderServiceConfirmOrderPaidResult() *OrderServiceConfirmOrderPaidResult {
	return &OrderServiceConfirmOrderPaidResult{}
}

func (p *OrderServiceConfirmOrderPaidResult) InitDefault() {
}

var OrderServiceConfirmOrderPaidResult_Success_DEFAULT *ConfirmOrderPaidResponse

func (p *OrderServiceConfirmOrderPaidResult) GetSuccess() (v *ConfirmOrderPaidResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceConfirmOrderPaidResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceConfirmOrderPaidResult) SetSuccess(x interface{}) {
	p.Success = x.(*ConfirmOrderPaidResponse)
}

func (p *OrderServiceConfirmOrderPaidResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceConfirmOrderPaidResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceConfirmOrderPaidResult(%+v)", *p)
}

var fieldIDToName_OrderServiceConfirmOrderPaidResult = map[int16]string{
	0: "success",
}

type OrderServiceGetOrderArgs struct {
	Request *GetOrderRequest `thrift:"request,1" frugal:"1,default,GetOrderRequest" json:"request"`
}

func NewOrderServiceGetOrderArgs() *OrderServiceGetOrderArgs {
	return &OrderServiceGetOrderArgs{}
}

func (p *OrderServiceGetOrderArgs) InitDefault() {
}

var OrderServiceGetOrderArgs_Request_DEFAULT *GetOrderRequest

func (p *OrderServiceGetOrderArgs) GetRequest() (v *GetOrderRequest) {
	if !p.IsSetRequest() {
		return OrderServiceGetOrderArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OrderServiceGetOrderArgs) SetRequest(val *GetOrderRequest) {
	p.Request = val
}

func (p *OrderServiceGetOrderArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OrderServiceGetOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderArgs = map[int16]string{
	1: "request",
}

type OrderServiceGetOrderResult struct {
	Success *GetOrderResponse `thrift:"success,0,optional" frugal:"0,optional,GetOrderResponse" json:"success,omitempty"`
}

func NewOrderServiceGetOrderResult() *OrderServiceGetOrderResult {
	return &OrderServiceGetOrderResult{}
}

func (p *OrderServiceGetOrderResult) InitDefault() {
}

var OrderServiceGetOrderResult_Success_DEFAULT *GetOrderResponse

func (p *OrderServiceGetOrderResult) GetSuccess() (v *GetOrderResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceGetOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceGetOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrderResponse)
}

func (p *OrderServiceGetOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceListOrdersArgs struct {
	Request *ListOrdersRequest `thrift:"request,1" frugal:"1,default,ListOrdersRequest" json:"request"`
}

func NewOrderServiceListOrdersArgs() *OrderServiceListOrdersArgs {
	return &OrderServiceListOrdersArgs{}
}

func (p *OrderServiceListOrdersArgs) InitDefault() {
}

var OrderServiceListOrdersArgs_Request_DEFAULT *ListOrdersRequest

func (p *OrderServiceListOrdersArgs) GetRequest() (v *ListOrdersRequest) {
	if !p.IsSetRequest() {
		return OrderServiceListOrdersArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OrderServiceListOrdersArgs) SetRequest(val *ListOrdersRequest) {
	p.Request = val
}

func (p *OrderServiceListOrdersArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OrderServiceListOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceListOrdersArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceListOrdersArgs = map[int16]string{
	1: "request",
}

type OrderServiceListOrdersResult struct {
	Success *ListOrdersResponse `thrift:"success,0,optional" frugal:"0,optional,ListOrdersResponse" json:"success,omitempty"`
}

func NewOrderServiceListOrdersResult() *OrderServiceListOrdersResult {
	return &OrderServiceListOrdersResult{}
}

func (p *OrderServiceListOrdersResult) InitDefault() {
}

var OrderServiceListOrdersResult_Success_DEFAULT *ListOrdersResponse

func (p *OrderServiceListOrdersResult) GetSuccess() (v *ListOrdersResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceListOrdersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceListOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListOrdersResponse)
}

func (p *OrderServiceListOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceListOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceListOrdersResult(%+v)", *p)
}

var fieldIDToName_OrderServiceListOrdersResult = map[int16]string{
	0: "success",
}

type OrderServiceCloseExpiredOrdersArgs struct {
	Request *CloseExpiredOrdersRequest `thrift:"request,1" frugal:"1,default,CloseExpiredOrdersRequest" json:"request"`
}

func NewOrderServiceCloseExpiredOrdersArgs() *OrderServiceCloseExpiredOrdersArgs {
	return &OrderServiceCloseExpiredOrdersArgs{}
}

func (p *OrderServiceCloseExpiredOrdersArgs) InitDefault() {
}

var OrderServiceCloseExpiredOrdersArgs_Request_DEFAULT *CloseExpiredOrdersRequest

func (p *OrderServiceCloseExpiredOrdersArgs) GetRequest() (v *CloseExpiredOrdersRequest) {
	if !p.IsSetRequest() {
		return OrderServiceCloseExpiredOrdersArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OrderServiceCloseExpiredOrdersArgs) SetRequest(val *CloseExpiredOrdersRequest) {
	p.Request = val
}

func (p *OrderServiceCloseExpiredOrdersArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OrderServiceCloseExpiredOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCloseExpiredOrdersArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCloseExpiredOrdersArgs = map[int16]string{
	1: "request",
}

type OrderServiceCloseExpiredOrdersResult struct {
	Success *CloseExpiredOrdersResponse `thrift:"success,0,optional" frugal:"0,optional,CloseExpiredOrdersResponse" json:"success,omitempty"`
}

func NewOrderServiceCloseExpiredOrdersResult() *OrderServiceCloseExpiredOrdersResult {
	return &OrderServiceCloseExpiredOrdersResult{}
}

func (p *OrderServiceCloseExpiredOrdersResult) InitDefault() {
}

var OrderServiceCloseExpiredOrdersResult_Success_DEFAULT *CloseExpiredOrdersResponse

func (p *OrderServiceCloseExpiredOrdersResult) GetSuccess() (v *CloseExpiredOrdersResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceCloseExpiredOrdersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCloseExpiredOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*CloseExpiredOrdersResponse)
}

func (p *OrderServiceCloseExpiredOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCloseExpiredOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCloseExpiredOrdersResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCloseExpiredOrdersResult = map[int16]string{
	0: "success",
}
