// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"context"
	"fmt"
	"meshcart/kitex_gen/meshcart/base"
)

type OrderItemInput struct {
	ProductId            int64  `thrift:"product_id,1" frugal:"1,default,i64" json:"product_id"`
	SkuId                int64  `thrift:"sku_id,2" frugal:"2,default,i64" json:"sku_id"`
	ProductTitleSnapshot string `thrift:"product_title_snapshot,3" frugal:"3,default,string" json:"product_title_snapshot"`
	SkuTitleSnapshot     string `thrift:"sku_title_snapshot,4" frugal:"4,default,string" json:"sku_title_snapshot"`
	SalePriceSnapshot    int64  `thrift:"sale_price_snapshot,5" frugal:"5,default,i64" json:"sale_price_snapshot"`
	Quantity             int32  `thrift:"quantity,6" frugal:"6,default,i32" json:"quantity"`
}

func NewOrderItemInput() *OrderItemInput {
	return &OrderItemInput{}
}

func (p *OrderItemInput) InitDefault() {
}

func (p *OrderItemInput) GetProductId() (v int64) {
	return p.ProductId
}

func (p *OrderItemInput) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *OrderItemInput) GetProductTitleSnapshot() (v string) {
	return p.ProductTitleSnapshot
}

func (p *OrderItemInput) GetSkuTitleSnapshot() (v string) {
	return p.SkuTitleSnapshot
}

func (p *OrderItemInput) GetSalePriceSnapshot() (v int64) {
	return p.SalePriceSnapshot
}

func (p *OrderItemInput) GetQuantity() (v int32) {
	return p.Quantity
}
func (p *OrderItemInput) SetProductId(val int64) {
	p.ProductId = val
}
func (p *OrderItemInput) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *OrderItemInput) SetProductTitleSnapshot(val string) {
	p.ProductTitleSnapshot = val
}
func (p *OrderItemInput) SetSkuTitleSnapshot(val string) {
	p.SkuTitleSnapshot = val
}
func (p *OrderItemInput) SetSalePriceSnapshot(val int64) {
	p.SalePriceSnapshot = val
}
func (p *OrderItemInput) SetQuantity(val int32) {
	p.Quantity = val
}

func (p *OrderItemInput) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderItemInput(%+v)", *p)
}

var fieldIDToName_OrderItemInput = map[int16]string{
	1: "product_id",
	2: "sku_id",
	3: "product_title_snapshot",
	4: "sku_title_snapshot",
	5: "sale_price_snapshot",
	6: "quantity",
}

type OrderItem struct {
	ItemId               int64  `thrift:"item_id,1" frugal:"1,default,i64" json:"item_id"`
	OrderId              int64  `thrift:"order_id,2" frugal:"2,default,i64" json:"order_id"`
	ProductId            int64  `thrift:"product_id,3" frugal:"3,default,i64" json:"product_id"`
	SkuId                int64  `thrift:"sku_id,4" frugal:"4,default,i64" json:"sku_id"`
	ProductTitleSnapshot string `thrift:"product_title_snapshot,5" frugal:"5,default,string" json:"product_title_snapshot"`
	SkuTitleSnapshot     string `thrift:"sku_title_snapshot,6" frugal:"6,default,string" json:"sku_title_snapshot"`
	SalePriceSnapshot    int64  `thrift:"sale_price_snapshot,7" frugal:"7,default,i64" json:"sale_price_snapshot"`
	Quantity             int32  `thrift:"quantity,8" frugal:"8,default,i32" json:"quantity"`
	SubtotalAmount       int64  `thrift:"subtotal_amount,9" frugal:"9,default,i64" json:"subtotal_amount"`
}

func NewOrderItem() *OrderItem {
	return &OrderItem{}
}

func (p *OrderItem) InitDefault() {
}

func (p *OrderItem) GetItemId() (v int64) {
	return p.ItemId
}

func (p *OrderItem) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *OrderItem) GetProductId() (v int64) {
	return p.ProductId
}

func (p *OrderItem) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *OrderItem) GetProductTitleSnapshot() (v string) {
	return p.ProductTitleSnapshot
}

func (p *OrderItem) GetSkuTitleSnapshot() (v string) {
	return p.SkuTitleSnapshot
}

func (p *OrderItem) GetSalePriceSnapshot() (v int64) {
	return p.SalePriceSnapshot
}

func (p *OrderItem) GetQuantity() (v int32) {
	return p.Quantity
}

func (p *OrderItem) GetSubtotalAmount() (v int64) {
	return p.SubtotalAmount
}
func (p *OrderItem) SetItemId(val int64) {
	p.ItemId = val
}
func (p *OrderItem) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *OrderItem) SetProductId(val int64) {
	p.ProductId = val
}
func (p *OrderItem) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *OrderItem) SetProductTitleSnapshot(val string) {
	p.ProductTitleSnapshot = val
}
func (p *OrderItem) SetSkuTitleSnapshot(val string) {
	p.SkuTitleSnapshot = val
}
func (p *OrderItem) SetSalePriceSnapshot(val int64) {
	p.SalePriceSnapshot = val
}
func (p *OrderItem) SetQuantity(val int32) {
	p.Quantity = val
}
func (p *OrderItem) SetSubtotalAmount(val int64) {
	p.SubtotalAmount = val
}

func (p *OrderItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderItem(%+v)", *p)
}

var fieldIDToName_OrderItem = map[int16]string{
	1: "item_id",
	2: "order_id",
	3: "product_id",
	4: "sku_id",
	5: "product_title_snapshot",
	6: "sku_title_snapshot",
	7: "sale_price_snapshot",
	8: "quantity",
	9: "subtotal_amount",
}

type Order struct {
	OrderId     int64        `thrift:"order_id,1" frugal:"1,default,i64" json:"order_id"`
	UserId      int64        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	Status      int32        `thrift:"status,3" frugal:"3,default,i32" json:"status"`
	TotalAmount int64        `thrift:"total_amount,4" frugal:"4,default,i64" json:"total_amount"`
	PayAmount   int64        `thrift:"pay_amount,5" frugal:"5,default,i64" json:"pay_amount"`
	ExpireAt    int64        `thrift:"expire_at,6" frugal:"6,default,i64" json:"expire_at"`
	Items       []*OrderItem `thrift:"items,7" frugal:"7,default,list<OrderItem>" json:"items"`
}

func NewOrder() *Order {
	return &Order{}
}

func (p *Order) InitDefault() {
}

func (p *Order) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *Order) GetUserId() (v int64) {
	return p.UserId
}

func (p *Order) GetStatus() (v int32) {
	return p.Status
}

func (p *Order) GetTotalAmount() (v int64) {
	return p.TotalAmount
}

func (p *Order) GetPayAmount() (v int64) {
	return p.PayAmount
}

func (p *Order) GetExpireAt() (v int64) {
	return p.ExpireAt
}

func (p *Order) GetItems() (v []*OrderItem) {
	return p.Items
}
func (p *Order) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *Order) SetUserId(val int64) {
	p.UserId = val
}
func (p *Order) SetStatus(val int32) {
	p.Status = val
}
func (p *Order) SetTotalAmount(val int64) {
	p.TotalAmount = val
}
func (p *Order) SetPayAmount(val int64) {
	p.PayAmount = val
}
func (p *Order) SetExpireAt(val int64) {
	p.ExpireAt = val
}
func (p *Order) SetItems(val []*OrderItem) {
	p.Items = val
}

func (p *Order) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Order(%+v)", *p)
}

var fieldIDToName_Order = map[int16]string{
	1: "order_id",
	2: "user_id",
	3: "status",
	4: "total_amount",
	5: "pay_amount",
	6: "expire_at",
	7: "items",
}

type CreateOrderRequest struct {
	UserId int64             `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Items  []*OrderItemInput `thrift:"items,2" frugal:"2,default,list<OrderItemInput>" json:"items"`
}

func NewCreateOrderRequest() *CreateOrderRequest {
	return &CreateOrderRequest{}
}

func (p *CreateOrderRequest) InitDefault() {
}

func (p *CreateOrderRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateOrderRequest) GetItems() (v []*OrderItemInput) {
	return p.Items
}
func (p *CreateOrderRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateOrderRequest) SetItems(val []*OrderItemInput) {
	p.Items = val
}

func (p *CreateOrderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderRequest(%+v)", *p)
}

var fieldIDToName_CreateOrderRequest = map[int16]string{
	1: "user_id",
	2: "items",
}

type CreateOrderResponse struct {
	Order *Order             `thrift:"order,1" frugal:"1,default,Order" json:"order"`
	Base  *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewCreateOrderResponse() *CreateOrderResponse {
	return &CreateOrderResponse{}
}

func (p *CreateOrderResponse) InitDefault() {
}

var CreateOrderResponse_Order_DEFAULT *Order

func (p *CreateOrderResponse) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return CreateOrderResponse_Order_DEFAULT
	}
	return p.Order
}

var CreateOrderResponse_Base_DEFAULT *base.BaseResponse

func (p *CreateOrderResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return CreateOrderResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *CreateOrderResponse) SetOrder(val *Order) {
	p.Order = val
}
func (p *CreateOrderResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *CreateOrderResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *CreateOrderResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateOrderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResponse(%+v)", *p)
}

var fieldIDToName_CreateOrderResponse = map[int16]string{
	1:   "order",
	255: "base",
}

type GetOrderRequest struct {
	UserId  int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	OrderId int64 `thrift:"order_id,2" frugal:"2,default,i64" json:"order_id"`
}

func NewGetOrderRequest() *GetOrderRequest {
	return &GetOrderRequest{}
}

func (p *GetOrderRequest) InitDefault() {
}

func (p *GetOrderRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetOrderRequest) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *GetOrderRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetOrderRequest) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *GetOrderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderRequest(%+v)", *p)
}

var fieldIDToName_GetOrderRequest = map[int16]string{
	1: "user_id",
	2: "order_id",
}

type GetOrderResponse struct {
	Order *Order             `thrift:"order,1" frugal:"1,default,Order" json:"order"`
	Base  *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewGetOrderResponse() *GetOrderResponse {
	return &GetOrderResponse{}
}

func (p *GetOrderResponse) InitDefault() {
}

var GetOrderResponse_Order_DEFAULT *Order

func (p *GetOrderResponse) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return GetOrderResponse_Order_DEFAULT
	}
	return p.Order
}

var GetOrderResponse_Base_DEFAULT *base.BaseResponse

func (p *GetOrderResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return GetOrderResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *GetOrderResponse) SetOrder(val *Order) {
	p.Order = val
}
func (p *GetOrderResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *GetOrderResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *GetOrderResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetOrderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderResponse(%+v)", *p)
}

var fieldIDToName_GetOrderResponse = map[int16]string{
	1:   "order",
	255: "base",
}

type ListOrdersRequest struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Page     int32 `thrift:"page,2" frugal:"2,default,i32" json:"page"`
	PageSize int32 `thrift:"page_size,3" frugal:"3,default,i32" json:"page_size"`
}

func NewListOrdersRequest() *ListOrdersRequest {
	return &ListOrdersRequest{}
}

func (p *ListOrdersRequest) InitDefault() {
}

func (p *ListOrdersRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *ListOrdersRequest) GetPage() (v int32) {
	return p.Page
}

func (p *ListOrdersRequest) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *ListOrdersRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *ListOrdersRequest) SetPage(val int32) {
	p.Page = val
}
func (p *ListOrdersRequest) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *ListOrdersRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersRequest(%+v)", *p)
}

var fieldIDToName_ListOrdersRequest = map[int16]string{
	1: "user_id",
	2: "page",
	3: "page_size",
}

type ListOrdersResponse struct {
	Orders []*Order           `thrift:"orders,1" frugal:"1,default,list<Order>" json:"orders"`
	Total  int64              `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	Base   *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewListOrdersResponse() *ListOrdersResponse {
	return &ListOrdersResponse{}
}

func (p *ListOrdersResponse) InitDefault() {
}

func (p *ListOrdersResponse) GetOrders() (v []*Order) {
	return p.Orders
}

func (p *ListOrdersResponse) GetTotal() (v int64) {
	return p.Total
}

var ListOrdersResponse_Base_DEFAULT *base.BaseResponse

func (p *ListOrdersResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return ListOrdersResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *ListOrdersResponse) SetOrders(val []*Order) {
	p.Orders = val
}
func (p *ListOrdersResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *ListOrdersResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *ListOrdersResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListOrdersResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersResponse(%+v)", *p)
}

var fieldIDToName_ListOrdersResponse = map[int16]string{
	1:   "orders",
	2:   "total",
	255: "base",
}

type OrderService interface {
	CreateOrder(ctx context.Context, request *CreateOrderRequest) (r *CreateOrderResponse, err error)

	GetOrder(ctx context.Context, request *GetOrderRequest) (r *GetOrderResponse, err error)

	ListOrders(ctx context.Context, request *ListOrdersRequest) (r *ListOrdersResponse, err error)
}

type OrderServiceCreateOrderArgs struct {
	Request *CreateOrderRequest `thrift:"request,1" frugal:"1,default,CreateOrderRequest" json:"request"`
}

func NewOrderServiceCreateOrderArgs() *OrderServiceCreateOrderArgs {
	return &OrderServiceCreateOrderArgs{}
}

func (p *OrderServiceCreateOrderArgs) InitDefault() {
}

var OrderServiceCreateOrderArgs_Request_DEFAULT *CreateOrderRequest

func (p *OrderServiceCreateOrderArgs) GetRequest() (v *CreateOrderRequest) {
	if !p.IsSetRequest() {
		return OrderServiceCreateOrderArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OrderServiceCreateOrderArgs) SetRequest(val *CreateOrderRequest) {
	p.Request = val
}

func (p *OrderServiceCreateOrderArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OrderServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderArgs = map[int16]string{
	1: "request",
}

type OrderServiceCreateOrderResult struct {
	Success *CreateOrderResponse `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResponse" json:"success,omitempty"`
}

func NewOrderServiceCreateOrderResult() *OrderServiceCreateOrderResult {
	return &OrderServiceCreateOrderResult{}
}

func (p *OrderServiceCreateOrderResult) InitDefault() {
}

var OrderServiceCreateOrderResult_Success_DEFAULT *CreateOrderResponse

func (p *OrderServiceCreateOrderResult) GetSuccess() (v *CreateOrderResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResponse)
}

func (p *OrderServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceGetOrderArgs struct {
	Request *GetOrderRequest `thrift:"request,1" frugal:"1,default,GetOrderRequest" json:"request"`
}

func NewOrderServiceGetOrderArgs() *OrderServiceGetOrderArgs {
	return &OrderServiceGetOrderArgs{}
}

func (p *OrderServiceGetOrderArgs) InitDefault() {
}

var OrderServiceGetOrderArgs_Request_DEFAULT *GetOrderRequest

func (p *OrderServiceGetOrderArgs) GetRequest() (v *GetOrderRequest) {
	if !p.IsSetRequest() {
		return OrderServiceGetOrderArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OrderServiceGetOrderArgs) SetRequest(val *GetOrderRequest) {
	p.Request = val
}

func (p *OrderServiceGetOrderArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OrderServiceGetOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderArgs = map[int16]string{
	1: "request",
}

type OrderServiceGetOrderResult struct {
	Success *GetOrderResponse `thrift:"success,0,optional" frugal:"0,optional,GetOrderResponse" json:"success,omitempty"`
}

func NewOrderServiceGetOrderResult() *OrderServiceGetOrderResult {
	return &OrderServiceGetOrderResult{}
}

func (p *OrderServiceGetOrderResult) InitDefault() {
}

var OrderServiceGetOrderResult_Success_DEFAULT *GetOrderResponse

func (p *OrderServiceGetOrderResult) GetSuccess() (v *GetOrderResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceGetOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceGetOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrderResponse)
}

func (p *OrderServiceGetOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceListOrdersArgs struct {
	Request *ListOrdersRequest `thrift:"request,1" frugal:"1,default,ListOrdersRequest" json:"request"`
}

func NewOrderServiceListOrdersArgs() *OrderServiceListOrdersArgs {
	return &OrderServiceListOrdersArgs{}
}

func (p *OrderServiceListOrdersArgs) InitDefault() {
}

var OrderServiceListOrdersArgs_Request_DEFAULT *ListOrdersRequest

func (p *OrderServiceListOrdersArgs) GetRequest() (v *ListOrdersRequest) {
	if !p.IsSetRequest() {
		return OrderServiceListOrdersArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OrderServiceListOrdersArgs) SetRequest(val *ListOrdersRequest) {
	p.Request = val
}

func (p *OrderServiceListOrdersArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OrderServiceListOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceListOrdersArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceListOrdersArgs = map[int16]string{
	1: "request",
}

type OrderServiceListOrdersResult struct {
	Success *ListOrdersResponse `thrift:"success,0,optional" frugal:"0,optional,ListOrdersResponse" json:"success,omitempty"`
}

func NewOrderServiceListOrdersResult() *OrderServiceListOrdersResult {
	return &OrderServiceListOrdersResult{}
}

func (p *OrderServiceListOrdersResult) InitDefault() {
}

var OrderServiceListOrdersResult_Success_DEFAULT *ListOrdersResponse

func (p *OrderServiceListOrdersResult) GetSuccess() (v *ListOrdersResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceListOrdersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceListOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListOrdersResponse)
}

func (p *OrderServiceListOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceListOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceListOrdersResult(%+v)", *p)
}

var fieldIDToName_OrderServiceListOrdersResult = map[int16]string{
	0: "success",
}
