// Code generated by Kitex v0.16.1. DO NOT EDIT.

package orderservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	order "meshcart/kitex_gen/meshcart/order"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateOrder(ctx context.Context, request *order.CreateOrderRequest, callOptions ...callopt.Option) (r *order.CreateOrderResponse, err error)
	CancelOrder(ctx context.Context, request *order.CancelOrderRequest, callOptions ...callopt.Option) (r *order.CancelOrderResponse, err error)
	GetOrder(ctx context.Context, request *order.GetOrderRequest, callOptions ...callopt.Option) (r *order.GetOrderResponse, err error)
	ListOrders(ctx context.Context, request *order.ListOrdersRequest, callOptions ...callopt.Option) (r *order.ListOrdersResponse, err error)
	CloseExpiredOrders(ctx context.Context, request *order.CloseExpiredOrdersRequest, callOptions ...callopt.Option) (r *order.CloseExpiredOrdersResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) CreateOrder(ctx context.Context, request *order.CreateOrderRequest, callOptions ...callopt.Option) (r *order.CreateOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, request)
}

func (p *kOrderServiceClient) CancelOrder(ctx context.Context, request *order.CancelOrderRequest, callOptions ...callopt.Option) (r *order.CancelOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelOrder(ctx, request)
}

func (p *kOrderServiceClient) GetOrder(ctx context.Context, request *order.GetOrderRequest, callOptions ...callopt.Option) (r *order.GetOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrder(ctx, request)
}

func (p *kOrderServiceClient) ListOrders(ctx context.Context, request *order.ListOrdersRequest, callOptions ...callopt.Option) (r *order.ListOrdersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOrders(ctx, request)
}

func (p *kOrderServiceClient) CloseExpiredOrders(ctx context.Context, request *order.CloseExpiredOrdersRequest, callOptions ...callopt.Option) (r *order.CloseExpiredOrdersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CloseExpiredOrders(ctx, request)
}
