// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"meshcart/kitex_gen/meshcart/base"
)

type UserLoginRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewUserLoginRequest() *UserLoginRequest {
	return &UserLoginRequest{}
}

func (p *UserLoginRequest) InitDefault() {
}

func (p *UserLoginRequest) GetUsername() (v string) {
	return p.Username
}

func (p *UserLoginRequest) GetPassword() (v string) {
	return p.Password
}
func (p *UserLoginRequest) SetUsername(val string) {
	p.Username = val
}
func (p *UserLoginRequest) SetPassword(val string) {
	p.Password = val
}

func (p *UserLoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserLoginRequest(%+v)", *p)
}

var fieldIDToName_UserLoginRequest = map[int16]string{
	1: "username",
	2: "password",
}

type UserLoginResponse struct {
	UserId   int64              `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Username string             `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Role     string             `thrift:"role,3" frugal:"3,default,string" json:"role"`
	Base     *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewUserLoginResponse() *UserLoginResponse {
	return &UserLoginResponse{}
}

func (p *UserLoginResponse) InitDefault() {
}

func (p *UserLoginResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserLoginResponse) GetUsername() (v string) {
	return p.Username
}

func (p *UserLoginResponse) GetRole() (v string) {
	return p.Role
}

var UserLoginResponse_Base_DEFAULT *base.BaseResponse

func (p *UserLoginResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return UserLoginResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *UserLoginResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserLoginResponse) SetUsername(val string) {
	p.Username = val
}
func (p *UserLoginResponse) SetRole(val string) {
	p.Role = val
}
func (p *UserLoginResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *UserLoginResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UserLoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserLoginResponse(%+v)", *p)
}

var fieldIDToName_UserLoginResponse = map[int16]string{
	1:   "user_id",
	2:   "username",
	3:   "role",
	255: "base",
}

type UserRegisterRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewUserRegisterRequest() *UserRegisterRequest {
	return &UserRegisterRequest{}
}

func (p *UserRegisterRequest) InitDefault() {
}

func (p *UserRegisterRequest) GetUsername() (v string) {
	return p.Username
}

func (p *UserRegisterRequest) GetPassword() (v string) {
	return p.Password
}
func (p *UserRegisterRequest) SetUsername(val string) {
	p.Username = val
}
func (p *UserRegisterRequest) SetPassword(val string) {
	p.Password = val
}

func (p *UserRegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserRegisterRequest(%+v)", *p)
}

var fieldIDToName_UserRegisterRequest = map[int16]string{
	1: "username",
	2: "password",
}

type UserRegisterResponse struct {
	Base *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewUserRegisterResponse() *UserRegisterResponse {
	return &UserRegisterResponse{}
}

func (p *UserRegisterResponse) InitDefault() {
}

var UserRegisterResponse_Base_DEFAULT *base.BaseResponse

func (p *UserRegisterResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return UserRegisterResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *UserRegisterResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *UserRegisterResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UserRegisterResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserRegisterResponse(%+v)", *p)
}

var fieldIDToName_UserRegisterResponse = map[int16]string{
	255: "base",
}

type UserGetRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewUserGetRequest() *UserGetRequest {
	return &UserGetRequest{}
}

func (p *UserGetRequest) InitDefault() {
}

func (p *UserGetRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *UserGetRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *UserGetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserGetRequest(%+v)", *p)
}

var fieldIDToName_UserGetRequest = map[int16]string{
	1: "user_id",
}

type UserGetResponse struct {
	UserId   int64              `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Username string             `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Role     string             `thrift:"role,3" frugal:"3,default,string" json:"role"`
	IsLocked bool               `thrift:"is_locked,4" frugal:"4,default,bool" json:"is_locked"`
	Base     *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewUserGetResponse() *UserGetResponse {
	return &UserGetResponse{}
}

func (p *UserGetResponse) InitDefault() {
}

func (p *UserGetResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserGetResponse) GetUsername() (v string) {
	return p.Username
}

func (p *UserGetResponse) GetRole() (v string) {
	return p.Role
}

func (p *UserGetResponse) GetIsLocked() (v bool) {
	return p.IsLocked
}

var UserGetResponse_Base_DEFAULT *base.BaseResponse

func (p *UserGetResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return UserGetResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *UserGetResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserGetResponse) SetUsername(val string) {
	p.Username = val
}
func (p *UserGetResponse) SetRole(val string) {
	p.Role = val
}
func (p *UserGetResponse) SetIsLocked(val bool) {
	p.IsLocked = val
}
func (p *UserGetResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *UserGetResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UserGetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserGetResponse(%+v)", *p)
}

var fieldIDToName_UserGetResponse = map[int16]string{
	1:   "user_id",
	2:   "username",
	3:   "role",
	4:   "is_locked",
	255: "base",
}

type UserUpdateRoleRequest struct {
	UserId int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Role   string `thrift:"role,2" frugal:"2,default,string" json:"role"`
}

func NewUserUpdateRoleRequest() *UserUpdateRoleRequest {
	return &UserUpdateRoleRequest{}
}

func (p *UserUpdateRoleRequest) InitDefault() {
}

func (p *UserUpdateRoleRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserUpdateRoleRequest) GetRole() (v string) {
	return p.Role
}
func (p *UserUpdateRoleRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserUpdateRoleRequest) SetRole(val string) {
	p.Role = val
}

func (p *UserUpdateRoleRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserUpdateRoleRequest(%+v)", *p)
}

var fieldIDToName_UserUpdateRoleRequest = map[int16]string{
	1: "user_id",
	2: "role",
}

type UserUpdateRoleResponse struct {
	Base *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewUserUpdateRoleResponse() *UserUpdateRoleResponse {
	return &UserUpdateRoleResponse{}
}

func (p *UserUpdateRoleResponse) InitDefault() {
}

var UserUpdateRoleResponse_Base_DEFAULT *base.BaseResponse

func (p *UserUpdateRoleResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return UserUpdateRoleResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *UserUpdateRoleResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *UserUpdateRoleResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UserUpdateRoleResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserUpdateRoleResponse(%+v)", *p)
}

var fieldIDToName_UserUpdateRoleResponse = map[int16]string{
	255: "base",
}

type UserService interface {
	Login(ctx context.Context, request *UserLoginRequest) (r *UserLoginResponse, err error)

	Register(ctx context.Context, request *UserRegisterRequest) (r *UserRegisterResponse, err error)

	GetUser(ctx context.Context, request *UserGetRequest) (r *UserGetResponse, err error)

	UpdateUserRole(ctx context.Context, request *UserUpdateRoleRequest) (r *UserUpdateRoleResponse, err error)
}

type UserServiceLoginArgs struct {
	Request *UserLoginRequest `thrift:"request,1" frugal:"1,default,UserLoginRequest" json:"request"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Request_DEFAULT *UserLoginRequest

func (p *UserServiceLoginArgs) GetRequest() (v *UserLoginRequest) {
	if !p.IsSetRequest() {
		return UserServiceLoginArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceLoginArgs) SetRequest(val *UserLoginRequest) {
	p.Request = val
}

func (p *UserServiceLoginArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "request",
}

type UserServiceLoginResult struct {
	Success *UserLoginResponse `thrift:"success,0,optional" frugal:"0,optional,UserLoginResponse" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *UserLoginResponse

func (p *UserServiceLoginResult) GetSuccess() (v *UserLoginResponse) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserLoginResponse)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceRegisterArgs struct {
	Request *UserRegisterRequest `thrift:"request,1" frugal:"1,default,UserRegisterRequest" json:"request"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Request_DEFAULT *UserRegisterRequest

func (p *UserServiceRegisterArgs) GetRequest() (v *UserRegisterRequest) {
	if !p.IsSetRequest() {
		return UserServiceRegisterArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceRegisterArgs) SetRequest(val *UserRegisterRequest) {
	p.Request = val
}

func (p *UserServiceRegisterArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "request",
}

type UserServiceRegisterResult struct {
	Success *UserRegisterResponse `thrift:"success,0,optional" frugal:"0,optional,UserRegisterResponse" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *UserRegisterResponse

func (p *UserServiceRegisterResult) GetSuccess() (v *UserRegisterResponse) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserRegisterResponse)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserArgs struct {
	Request *UserGetRequest `thrift:"request,1" frugal:"1,default,UserGetRequest" json:"request"`
}

func NewUserServiceGetUserArgs() *UserServiceGetUserArgs {
	return &UserServiceGetUserArgs{}
}

func (p *UserServiceGetUserArgs) InitDefault() {
}

var UserServiceGetUserArgs_Request_DEFAULT *UserGetRequest

func (p *UserServiceGetUserArgs) GetRequest() (v *UserGetRequest) {
	if !p.IsSetRequest() {
		return UserServiceGetUserArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceGetUserArgs) SetRequest(val *UserGetRequest) {
	p.Request = val
}

func (p *UserServiceGetUserArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserArgs = map[int16]string{
	1: "request",
}

type UserServiceGetUserResult struct {
	Success *UserGetResponse `thrift:"success,0,optional" frugal:"0,optional,UserGetResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserResult() *UserServiceGetUserResult {
	return &UserServiceGetUserResult{}
}

func (p *UserServiceGetUserResult) InitDefault() {
}

var UserServiceGetUserResult_Success_DEFAULT *UserGetResponse

func (p *UserServiceGetUserResult) GetSuccess() (v *UserGetResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserGetResponse)
}

func (p *UserServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateUserRoleArgs struct {
	Request *UserUpdateRoleRequest `thrift:"request,1" frugal:"1,default,UserUpdateRoleRequest" json:"request"`
}

func NewUserServiceUpdateUserRoleArgs() *UserServiceUpdateUserRoleArgs {
	return &UserServiceUpdateUserRoleArgs{}
}

func (p *UserServiceUpdateUserRoleArgs) InitDefault() {
}

var UserServiceUpdateUserRoleArgs_Request_DEFAULT *UserUpdateRoleRequest

func (p *UserServiceUpdateUserRoleArgs) GetRequest() (v *UserUpdateRoleRequest) {
	if !p.IsSetRequest() {
		return UserServiceUpdateUserRoleArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceUpdateUserRoleArgs) SetRequest(val *UserUpdateRoleRequest) {
	p.Request = val
}

func (p *UserServiceUpdateUserRoleArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceUpdateUserRoleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserRoleArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserRoleArgs = map[int16]string{
	1: "request",
}

type UserServiceUpdateUserRoleResult struct {
	Success *UserUpdateRoleResponse `thrift:"success,0,optional" frugal:"0,optional,UserUpdateRoleResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateUserRoleResult() *UserServiceUpdateUserRoleResult {
	return &UserServiceUpdateUserRoleResult{}
}

func (p *UserServiceUpdateUserRoleResult) InitDefault() {
}

var UserServiceUpdateUserRoleResult_Success_DEFAULT *UserUpdateRoleResponse

func (p *UserServiceUpdateUserRoleResult) GetSuccess() (v *UserUpdateRoleResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserRoleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateUserRoleResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserUpdateRoleResponse)
}

func (p *UserServiceUpdateUserRoleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserRoleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserRoleResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserRoleResult = map[int16]string{
	0: "success",
}
