// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"meshcart/kitex_gen/meshcart/base"
)

type UserLoginRequest struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewUserLoginRequest() *UserLoginRequest {
	return &UserLoginRequest{}
}

func (p *UserLoginRequest) InitDefault() {
}

func (p *UserLoginRequest) GetUsername() (v string) {
	return p.Username
}

func (p *UserLoginRequest) GetPassword() (v string) {
	return p.Password
}
func (p *UserLoginRequest) SetUsername(val string) {
	p.Username = val
}
func (p *UserLoginRequest) SetPassword(val string) {
	p.Password = val
}

func (p *UserLoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserLoginRequest(%+v)", *p)
}

var fieldIDToName_UserLoginRequest = map[int16]string{
	1: "username",
	2: "password",
}

type UserLoginResponse struct {
	Base *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewUserLoginResponse() *UserLoginResponse {
	return &UserLoginResponse{}
}

func (p *UserLoginResponse) InitDefault() {
}

var UserLoginResponse_Base_DEFAULT *base.BaseResponse

func (p *UserLoginResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return UserLoginResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *UserLoginResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *UserLoginResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UserLoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserLoginResponse(%+v)", *p)
}

var fieldIDToName_UserLoginResponse = map[int16]string{
	255: "base",
}

type UserService interface {
	Login(ctx context.Context, request *UserLoginRequest) (r *UserLoginResponse, err error)
}

type UserServiceLoginArgs struct {
	Request *UserLoginRequest `thrift:"request,1" frugal:"1,default,UserLoginRequest" json:"request"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Request_DEFAULT *UserLoginRequest

func (p *UserServiceLoginArgs) GetRequest() (v *UserLoginRequest) {
	if !p.IsSetRequest() {
		return UserServiceLoginArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceLoginArgs) SetRequest(val *UserLoginRequest) {
	p.Request = val
}

func (p *UserServiceLoginArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "request",
}

type UserServiceLoginResult struct {
	Success *UserLoginResponse `thrift:"success,0,optional" frugal:"0,optional,UserLoginResponse" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *UserLoginResponse

func (p *UserServiceLoginResult) GetSuccess() (v *UserLoginResponse) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserLoginResponse)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}
