#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT_DIR"

export APP_ENV="${APP_ENV:-dev}"
export LOG_LEVEL="${LOG_LEVEL:-info}"
export LOG_DIR="${LOG_DIR:-logs}"
export OTEL_EXPORTER_OTLP_ENDPOINT="${OTEL_EXPORTER_OTLP_ENDPOINT:-localhost:4319}"
export ORDER_METRICS_ADDR="${ORDER_METRICS_ADDR:-:9096}"
export ORDER_SERVICE_CONFIG="${ORDER_SERVICE_CONFIG:-services/order-service/config/order-service.local.yaml}"
export ORDER_SERVICE_CONFIG_SOURCE="${ORDER_SERVICE_CONFIG_SOURCE:-file}"
export ORDER_RPC_SERVICE="${ORDER_RPC_SERVICE:-meshcart.order}"
export ORDER_SERVICE_ADDR="${ORDER_SERVICE_ADDR:-127.0.0.1:8892}"
export ORDER_SERVICE_REGISTRY="${ORDER_SERVICE_REGISTRY:-consul}"
export CONSUL_ADDR="${CONSUL_ADDR:-127.0.0.1:8500}"
export ORDER_SERVICE_CONSUL_TCP_CHECK="${ORDER_SERVICE_CONSUL_TCP_CHECK:-false}"
export ORDER_SERVICE_SHUTDOWN_TIMEOUT_MS="${ORDER_SERVICE_SHUTDOWN_TIMEOUT_MS:-5000}"
export ORDER_SERVICE_PREFLIGHT_TIMEOUT_MS="${ORDER_SERVICE_PREFLIGHT_TIMEOUT_MS:-1500}"
export ORDER_SERVICE_DRAIN_TIMEOUT_MS="${ORDER_SERVICE_DRAIN_TIMEOUT_MS:-500}"

if [[ ! -f "$ORDER_SERVICE_CONFIG" ]]; then
  echo "[ERROR] config file not found: $ORDER_SERVICE_CONFIG" >&2
  exit 1
fi

echo "[INFO] starting order-service"
echo "[INFO] APP_ENV=$APP_ENV LOG_LEVEL=$LOG_LEVEL LOG_DIR=$LOG_DIR OTEL_EXPORTER_OTLP_ENDPOINT=$OTEL_EXPORTER_OTLP_ENDPOINT"
echo "[INFO] ORDER_METRICS_ADDR=$ORDER_METRICS_ADDR ORDER_SERVICE_CONFIG=$ORDER_SERVICE_CONFIG ORDER_SERVICE_CONFIG_SOURCE=$ORDER_SERVICE_CONFIG_SOURCE"
echo "[INFO] ORDER_RPC_SERVICE=$ORDER_RPC_SERVICE ORDER_SERVICE_ADDR=$ORDER_SERVICE_ADDR ORDER_SERVICE_REGISTRY=$ORDER_SERVICE_REGISTRY CONSUL_ADDR=$CONSUL_ADDR ORDER_SERVICE_CONSUL_TCP_CHECK=$ORDER_SERVICE_CONSUL_TCP_CHECK"
echo "[INFO] ORDER_SERVICE_SHUTDOWN_TIMEOUT_MS=$ORDER_SERVICE_SHUTDOWN_TIMEOUT_MS ORDER_SERVICE_PREFLIGHT_TIMEOUT_MS=$ORDER_SERVICE_PREFLIGHT_TIMEOUT_MS ORDER_SERVICE_DRAIN_TIMEOUT_MS=$ORDER_SERVICE_DRAIN_TIMEOUT_MS healthz=http://127.0.0.1${ORDER_METRICS_ADDR}/healthz readyz=http://127.0.0.1${ORDER_METRICS_ADDR}/readyz metrics=http://127.0.0.1${ORDER_METRICS_ADDR}/metrics"

exec go run ./services/order-service/rpc
