// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package inventory

import (
	"context"
	"fmt"
	"meshcart/kitex_gen/meshcart/base"
)

type SkuStock struct {
	SkuId          int64 `thrift:"sku_id,1" frugal:"1,default,i64" json:"sku_id"`
	TotalStock     int64 `thrift:"total_stock,2" frugal:"2,default,i64" json:"total_stock"`
	ReservedStock  int64 `thrift:"reserved_stock,3" frugal:"3,default,i64" json:"reserved_stock"`
	AvailableStock int64 `thrift:"available_stock,4" frugal:"4,default,i64" json:"available_stock"`
	SaleableStock  int64 `thrift:"saleable_stock,5" frugal:"5,default,i64" json:"saleable_stock"`
}

func NewSkuStock() *SkuStock {
	return &SkuStock{}
}

func (p *SkuStock) InitDefault() {
}

func (p *SkuStock) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *SkuStock) GetTotalStock() (v int64) {
	return p.TotalStock
}

func (p *SkuStock) GetReservedStock() (v int64) {
	return p.ReservedStock
}

func (p *SkuStock) GetAvailableStock() (v int64) {
	return p.AvailableStock
}

func (p *SkuStock) GetSaleableStock() (v int64) {
	return p.SaleableStock
}
func (p *SkuStock) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *SkuStock) SetTotalStock(val int64) {
	p.TotalStock = val
}
func (p *SkuStock) SetReservedStock(val int64) {
	p.ReservedStock = val
}
func (p *SkuStock) SetAvailableStock(val int64) {
	p.AvailableStock = val
}
func (p *SkuStock) SetSaleableStock(val int64) {
	p.SaleableStock = val
}

func (p *SkuStock) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SkuStock(%+v)", *p)
}

var fieldIDToName_SkuStock = map[int16]string{
	1: "sku_id",
	2: "total_stock",
	3: "reserved_stock",
	4: "available_stock",
	5: "saleable_stock",
}

type GetSkuStockRequest struct {
	SkuId int64 `thrift:"sku_id,1" frugal:"1,default,i64" json:"sku_id"`
}

func NewGetSkuStockRequest() *GetSkuStockRequest {
	return &GetSkuStockRequest{}
}

func (p *GetSkuStockRequest) InitDefault() {
}

func (p *GetSkuStockRequest) GetSkuId() (v int64) {
	return p.SkuId
}
func (p *GetSkuStockRequest) SetSkuId(val int64) {
	p.SkuId = val
}

func (p *GetSkuStockRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetSkuStockRequest(%+v)", *p)
}

var fieldIDToName_GetSkuStockRequest = map[int16]string{
	1: "sku_id",
}

type GetSkuStockResponse struct {
	Stock *SkuStock          `thrift:"stock,1" frugal:"1,default,SkuStock" json:"stock"`
	Base  *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewGetSkuStockResponse() *GetSkuStockResponse {
	return &GetSkuStockResponse{}
}

func (p *GetSkuStockResponse) InitDefault() {
}

var GetSkuStockResponse_Stock_DEFAULT *SkuStock

func (p *GetSkuStockResponse) GetStock() (v *SkuStock) {
	if !p.IsSetStock() {
		return GetSkuStockResponse_Stock_DEFAULT
	}
	return p.Stock
}

var GetSkuStockResponse_Base_DEFAULT *base.BaseResponse

func (p *GetSkuStockResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return GetSkuStockResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *GetSkuStockResponse) SetStock(val *SkuStock) {
	p.Stock = val
}
func (p *GetSkuStockResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *GetSkuStockResponse) IsSetStock() bool {
	return p.Stock != nil
}

func (p *GetSkuStockResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetSkuStockResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetSkuStockResponse(%+v)", *p)
}

var fieldIDToName_GetSkuStockResponse = map[int16]string{
	1:   "stock",
	255: "base",
}

type BatchGetSkuStockRequest struct {
	SkuIds []int64 `thrift:"sku_ids,1" frugal:"1,default,list<i64>" json:"sku_ids"`
}

func NewBatchGetSkuStockRequest() *BatchGetSkuStockRequest {
	return &BatchGetSkuStockRequest{}
}

func (p *BatchGetSkuStockRequest) InitDefault() {
}

func (p *BatchGetSkuStockRequest) GetSkuIds() (v []int64) {
	return p.SkuIds
}
func (p *BatchGetSkuStockRequest) SetSkuIds(val []int64) {
	p.SkuIds = val
}

func (p *BatchGetSkuStockRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchGetSkuStockRequest(%+v)", *p)
}

var fieldIDToName_BatchGetSkuStockRequest = map[int16]string{
	1: "sku_ids",
}

type BatchGetSkuStockResponse struct {
	Stocks []*SkuStock        `thrift:"stocks,1" frugal:"1,default,list<SkuStock>" json:"stocks"`
	Base   *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewBatchGetSkuStockResponse() *BatchGetSkuStockResponse {
	return &BatchGetSkuStockResponse{}
}

func (p *BatchGetSkuStockResponse) InitDefault() {
}

func (p *BatchGetSkuStockResponse) GetStocks() (v []*SkuStock) {
	return p.Stocks
}

var BatchGetSkuStockResponse_Base_DEFAULT *base.BaseResponse

func (p *BatchGetSkuStockResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return BatchGetSkuStockResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *BatchGetSkuStockResponse) SetStocks(val []*SkuStock) {
	p.Stocks = val
}
func (p *BatchGetSkuStockResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *BatchGetSkuStockResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *BatchGetSkuStockResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchGetSkuStockResponse(%+v)", *p)
}

var fieldIDToName_BatchGetSkuStockResponse = map[int16]string{
	1:   "stocks",
	255: "base",
}

type CheckSaleableStockRequest struct {
	SkuId    int64 `thrift:"sku_id,1" frugal:"1,default,i64" json:"sku_id"`
	Quantity int32 `thrift:"quantity,2" frugal:"2,default,i32" json:"quantity"`
}

func NewCheckSaleableStockRequest() *CheckSaleableStockRequest {
	return &CheckSaleableStockRequest{}
}

func (p *CheckSaleableStockRequest) InitDefault() {
}

func (p *CheckSaleableStockRequest) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *CheckSaleableStockRequest) GetQuantity() (v int32) {
	return p.Quantity
}
func (p *CheckSaleableStockRequest) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *CheckSaleableStockRequest) SetQuantity(val int32) {
	p.Quantity = val
}

func (p *CheckSaleableStockRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckSaleableStockRequest(%+v)", *p)
}

var fieldIDToName_CheckSaleableStockRequest = map[int16]string{
	1: "sku_id",
	2: "quantity",
}

type CheckSaleableStockResponse struct {
	Saleable       bool               `thrift:"saleable,1" frugal:"1,default,bool" json:"saleable"`
	AvailableStock int64              `thrift:"available_stock,2" frugal:"2,default,i64" json:"available_stock"`
	Base           *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewCheckSaleableStockResponse() *CheckSaleableStockResponse {
	return &CheckSaleableStockResponse{}
}

func (p *CheckSaleableStockResponse) InitDefault() {
}

func (p *CheckSaleableStockResponse) GetSaleable() (v bool) {
	return p.Saleable
}

func (p *CheckSaleableStockResponse) GetAvailableStock() (v int64) {
	return p.AvailableStock
}

var CheckSaleableStockResponse_Base_DEFAULT *base.BaseResponse

func (p *CheckSaleableStockResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return CheckSaleableStockResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *CheckSaleableStockResponse) SetSaleable(val bool) {
	p.Saleable = val
}
func (p *CheckSaleableStockResponse) SetAvailableStock(val int64) {
	p.AvailableStock = val
}
func (p *CheckSaleableStockResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *CheckSaleableStockResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *CheckSaleableStockResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckSaleableStockResponse(%+v)", *p)
}

var fieldIDToName_CheckSaleableStockResponse = map[int16]string{
	1:   "saleable",
	2:   "available_stock",
	255: "base",
}

type InventoryService interface {
	GetSkuStock(ctx context.Context, request *GetSkuStockRequest) (r *GetSkuStockResponse, err error)

	BatchGetSkuStock(ctx context.Context, request *BatchGetSkuStockRequest) (r *BatchGetSkuStockResponse, err error)

	CheckSaleableStock(ctx context.Context, request *CheckSaleableStockRequest) (r *CheckSaleableStockResponse, err error)
}

type InventoryServiceGetSkuStockArgs struct {
	Request *GetSkuStockRequest `thrift:"request,1" frugal:"1,default,GetSkuStockRequest" json:"request"`
}

func NewInventoryServiceGetSkuStockArgs() *InventoryServiceGetSkuStockArgs {
	return &InventoryServiceGetSkuStockArgs{}
}

func (p *InventoryServiceGetSkuStockArgs) InitDefault() {
}

var InventoryServiceGetSkuStockArgs_Request_DEFAULT *GetSkuStockRequest

func (p *InventoryServiceGetSkuStockArgs) GetRequest() (v *GetSkuStockRequest) {
	if !p.IsSetRequest() {
		return InventoryServiceGetSkuStockArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *InventoryServiceGetSkuStockArgs) SetRequest(val *GetSkuStockRequest) {
	p.Request = val
}

func (p *InventoryServiceGetSkuStockArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *InventoryServiceGetSkuStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceGetSkuStockArgs(%+v)", *p)
}

var fieldIDToName_InventoryServiceGetSkuStockArgs = map[int16]string{
	1: "request",
}

type InventoryServiceGetSkuStockResult struct {
	Success *GetSkuStockResponse `thrift:"success,0,optional" frugal:"0,optional,GetSkuStockResponse" json:"success,omitempty"`
}

func NewInventoryServiceGetSkuStockResult() *InventoryServiceGetSkuStockResult {
	return &InventoryServiceGetSkuStockResult{}
}

func (p *InventoryServiceGetSkuStockResult) InitDefault() {
}

var InventoryServiceGetSkuStockResult_Success_DEFAULT *GetSkuStockResponse

func (p *InventoryServiceGetSkuStockResult) GetSuccess() (v *GetSkuStockResponse) {
	if !p.IsSetSuccess() {
		return InventoryServiceGetSkuStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InventoryServiceGetSkuStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetSkuStockResponse)
}

func (p *InventoryServiceGetSkuStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InventoryServiceGetSkuStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceGetSkuStockResult(%+v)", *p)
}

var fieldIDToName_InventoryServiceGetSkuStockResult = map[int16]string{
	0: "success",
}

type InventoryServiceBatchGetSkuStockArgs struct {
	Request *BatchGetSkuStockRequest `thrift:"request,1" frugal:"1,default,BatchGetSkuStockRequest" json:"request"`
}

func NewInventoryServiceBatchGetSkuStockArgs() *InventoryServiceBatchGetSkuStockArgs {
	return &InventoryServiceBatchGetSkuStockArgs{}
}

func (p *InventoryServiceBatchGetSkuStockArgs) InitDefault() {
}

var InventoryServiceBatchGetSkuStockArgs_Request_DEFAULT *BatchGetSkuStockRequest

func (p *InventoryServiceBatchGetSkuStockArgs) GetRequest() (v *BatchGetSkuStockRequest) {
	if !p.IsSetRequest() {
		return InventoryServiceBatchGetSkuStockArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *InventoryServiceBatchGetSkuStockArgs) SetRequest(val *BatchGetSkuStockRequest) {
	p.Request = val
}

func (p *InventoryServiceBatchGetSkuStockArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *InventoryServiceBatchGetSkuStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceBatchGetSkuStockArgs(%+v)", *p)
}

var fieldIDToName_InventoryServiceBatchGetSkuStockArgs = map[int16]string{
	1: "request",
}

type InventoryServiceBatchGetSkuStockResult struct {
	Success *BatchGetSkuStockResponse `thrift:"success,0,optional" frugal:"0,optional,BatchGetSkuStockResponse" json:"success,omitempty"`
}

func NewInventoryServiceBatchGetSkuStockResult() *InventoryServiceBatchGetSkuStockResult {
	return &InventoryServiceBatchGetSkuStockResult{}
}

func (p *InventoryServiceBatchGetSkuStockResult) InitDefault() {
}

var InventoryServiceBatchGetSkuStockResult_Success_DEFAULT *BatchGetSkuStockResponse

func (p *InventoryServiceBatchGetSkuStockResult) GetSuccess() (v *BatchGetSkuStockResponse) {
	if !p.IsSetSuccess() {
		return InventoryServiceBatchGetSkuStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InventoryServiceBatchGetSkuStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchGetSkuStockResponse)
}

func (p *InventoryServiceBatchGetSkuStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InventoryServiceBatchGetSkuStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceBatchGetSkuStockResult(%+v)", *p)
}

var fieldIDToName_InventoryServiceBatchGetSkuStockResult = map[int16]string{
	0: "success",
}

type InventoryServiceCheckSaleableStockArgs struct {
	Request *CheckSaleableStockRequest `thrift:"request,1" frugal:"1,default,CheckSaleableStockRequest" json:"request"`
}

func NewInventoryServiceCheckSaleableStockArgs() *InventoryServiceCheckSaleableStockArgs {
	return &InventoryServiceCheckSaleableStockArgs{}
}

func (p *InventoryServiceCheckSaleableStockArgs) InitDefault() {
}

var InventoryServiceCheckSaleableStockArgs_Request_DEFAULT *CheckSaleableStockRequest

func (p *InventoryServiceCheckSaleableStockArgs) GetRequest() (v *CheckSaleableStockRequest) {
	if !p.IsSetRequest() {
		return InventoryServiceCheckSaleableStockArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *InventoryServiceCheckSaleableStockArgs) SetRequest(val *CheckSaleableStockRequest) {
	p.Request = val
}

func (p *InventoryServiceCheckSaleableStockArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *InventoryServiceCheckSaleableStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceCheckSaleableStockArgs(%+v)", *p)
}

var fieldIDToName_InventoryServiceCheckSaleableStockArgs = map[int16]string{
	1: "request",
}

type InventoryServiceCheckSaleableStockResult struct {
	Success *CheckSaleableStockResponse `thrift:"success,0,optional" frugal:"0,optional,CheckSaleableStockResponse" json:"success,omitempty"`
}

func NewInventoryServiceCheckSaleableStockResult() *InventoryServiceCheckSaleableStockResult {
	return &InventoryServiceCheckSaleableStockResult{}
}

func (p *InventoryServiceCheckSaleableStockResult) InitDefault() {
}

var InventoryServiceCheckSaleableStockResult_Success_DEFAULT *CheckSaleableStockResponse

func (p *InventoryServiceCheckSaleableStockResult) GetSuccess() (v *CheckSaleableStockResponse) {
	if !p.IsSetSuccess() {
		return InventoryServiceCheckSaleableStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InventoryServiceCheckSaleableStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*CheckSaleableStockResponse)
}

func (p *InventoryServiceCheckSaleableStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InventoryServiceCheckSaleableStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceCheckSaleableStockResult(%+v)", *p)
}

var fieldIDToName_InventoryServiceCheckSaleableStockResult = map[int16]string{
	0: "success",
}
