// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package product

import (
	"context"
	"fmt"
	"meshcart/kitex_gen/meshcart/base"
)

type ProductSkuAttr struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	SkuId     int64  `thrift:"sku_id,2" frugal:"2,default,i64" json:"sku_id"`
	AttrName  string `thrift:"attr_name,3" frugal:"3,default,string" json:"attr_name"`
	AttrValue string `thrift:"attr_value,4" frugal:"4,default,string" json:"attr_value"`
	Sort      int32  `thrift:"sort,5" frugal:"5,default,i32" json:"sort"`
}

func NewProductSkuAttr() *ProductSkuAttr {
	return &ProductSkuAttr{}
}

func (p *ProductSkuAttr) InitDefault() {
}

func (p *ProductSkuAttr) GetId() (v int64) {
	return p.Id
}

func (p *ProductSkuAttr) GetSkuId() (v int64) {
	return p.SkuId
}

func (p *ProductSkuAttr) GetAttrName() (v string) {
	return p.AttrName
}

func (p *ProductSkuAttr) GetAttrValue() (v string) {
	return p.AttrValue
}

func (p *ProductSkuAttr) GetSort() (v int32) {
	return p.Sort
}
func (p *ProductSkuAttr) SetId(val int64) {
	p.Id = val
}
func (p *ProductSkuAttr) SetSkuId(val int64) {
	p.SkuId = val
}
func (p *ProductSkuAttr) SetAttrName(val string) {
	p.AttrName = val
}
func (p *ProductSkuAttr) SetAttrValue(val string) {
	p.AttrValue = val
}
func (p *ProductSkuAttr) SetSort(val int32) {
	p.Sort = val
}

func (p *ProductSkuAttr) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductSkuAttr(%+v)", *p)
}

var fieldIDToName_ProductSkuAttr = map[int16]string{
	1: "id",
	2: "sku_id",
	3: "attr_name",
	4: "attr_value",
	5: "sort",
}

type ProductSku struct {
	Id          int64             `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	SpuId       int64             `thrift:"spu_id,2" frugal:"2,default,i64" json:"spu_id"`
	SkuCode     string            `thrift:"sku_code,3" frugal:"3,default,string" json:"sku_code"`
	Title       string            `thrift:"title,4" frugal:"4,default,string" json:"title"`
	SalePrice   int64             `thrift:"sale_price,5" frugal:"5,default,i64" json:"sale_price"`
	MarketPrice int64             `thrift:"market_price,6" frugal:"6,default,i64" json:"market_price"`
	Status      int32             `thrift:"status,7" frugal:"7,default,i32" json:"status"`
	CoverUrl    string            `thrift:"cover_url,8" frugal:"8,default,string" json:"cover_url"`
	Attrs       []*ProductSkuAttr `thrift:"attrs,9" frugal:"9,default,list<ProductSkuAttr>" json:"attrs"`
}

func NewProductSku() *ProductSku {
	return &ProductSku{}
}

func (p *ProductSku) InitDefault() {
}

func (p *ProductSku) GetId() (v int64) {
	return p.Id
}

func (p *ProductSku) GetSpuId() (v int64) {
	return p.SpuId
}

func (p *ProductSku) GetSkuCode() (v string) {
	return p.SkuCode
}

func (p *ProductSku) GetTitle() (v string) {
	return p.Title
}

func (p *ProductSku) GetSalePrice() (v int64) {
	return p.SalePrice
}

func (p *ProductSku) GetMarketPrice() (v int64) {
	return p.MarketPrice
}

func (p *ProductSku) GetStatus() (v int32) {
	return p.Status
}

func (p *ProductSku) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *ProductSku) GetAttrs() (v []*ProductSkuAttr) {
	return p.Attrs
}
func (p *ProductSku) SetId(val int64) {
	p.Id = val
}
func (p *ProductSku) SetSpuId(val int64) {
	p.SpuId = val
}
func (p *ProductSku) SetSkuCode(val string) {
	p.SkuCode = val
}
func (p *ProductSku) SetTitle(val string) {
	p.Title = val
}
func (p *ProductSku) SetSalePrice(val int64) {
	p.SalePrice = val
}
func (p *ProductSku) SetMarketPrice(val int64) {
	p.MarketPrice = val
}
func (p *ProductSku) SetStatus(val int32) {
	p.Status = val
}
func (p *ProductSku) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *ProductSku) SetAttrs(val []*ProductSkuAttr) {
	p.Attrs = val
}

func (p *ProductSku) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductSku(%+v)", *p)
}

var fieldIDToName_ProductSku = map[int16]string{
	1: "id",
	2: "spu_id",
	3: "sku_code",
	4: "title",
	5: "sale_price",
	6: "market_price",
	7: "status",
	8: "cover_url",
	9: "attrs",
}

type Product struct {
	Id          int64         `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Title       string        `thrift:"title,2" frugal:"2,default,string" json:"title"`
	SubTitle    string        `thrift:"sub_title,3" frugal:"3,default,string" json:"sub_title"`
	CategoryId  int64         `thrift:"category_id,4" frugal:"4,default,i64" json:"category_id"`
	Brand       string        `thrift:"brand,5" frugal:"5,default,string" json:"brand"`
	Description string        `thrift:"description,6" frugal:"6,default,string" json:"description"`
	Status      int32         `thrift:"status,7" frugal:"7,default,i32" json:"status"`
	Skus        []*ProductSku `thrift:"skus,8" frugal:"8,default,list<ProductSku>" json:"skus"`
	CreatorId   int64         `thrift:"creator_id,9" frugal:"9,default,i64" json:"creator_id"`
}

func NewProduct() *Product {
	return &Product{}
}

func (p *Product) InitDefault() {
}

func (p *Product) GetId() (v int64) {
	return p.Id
}

func (p *Product) GetTitle() (v string) {
	return p.Title
}

func (p *Product) GetSubTitle() (v string) {
	return p.SubTitle
}

func (p *Product) GetCategoryId() (v int64) {
	return p.CategoryId
}

func (p *Product) GetBrand() (v string) {
	return p.Brand
}

func (p *Product) GetDescription() (v string) {
	return p.Description
}

func (p *Product) GetStatus() (v int32) {
	return p.Status
}

func (p *Product) GetSkus() (v []*ProductSku) {
	return p.Skus
}

func (p *Product) GetCreatorId() (v int64) {
	return p.CreatorId
}
func (p *Product) SetId(val int64) {
	p.Id = val
}
func (p *Product) SetTitle(val string) {
	p.Title = val
}
func (p *Product) SetSubTitle(val string) {
	p.SubTitle = val
}
func (p *Product) SetCategoryId(val int64) {
	p.CategoryId = val
}
func (p *Product) SetBrand(val string) {
	p.Brand = val
}
func (p *Product) SetDescription(val string) {
	p.Description = val
}
func (p *Product) SetStatus(val int32) {
	p.Status = val
}
func (p *Product) SetSkus(val []*ProductSku) {
	p.Skus = val
}
func (p *Product) SetCreatorId(val int64) {
	p.CreatorId = val
}

func (p *Product) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Product(%+v)", *p)
}

var fieldIDToName_Product = map[int16]string{
	1: "id",
	2: "title",
	3: "sub_title",
	4: "category_id",
	5: "brand",
	6: "description",
	7: "status",
	8: "skus",
	9: "creator_id",
}

type ProductListItem struct {
	Id           int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Title        string `thrift:"title,2" frugal:"2,default,string" json:"title"`
	SubTitle     string `thrift:"sub_title,3" frugal:"3,default,string" json:"sub_title"`
	CategoryId   int64  `thrift:"category_id,4" frugal:"4,default,i64" json:"category_id"`
	Brand        string `thrift:"brand,5" frugal:"5,default,string" json:"brand"`
	Status       int32  `thrift:"status,6" frugal:"6,default,i32" json:"status"`
	MinSalePrice int64  `thrift:"min_sale_price,7" frugal:"7,default,i64" json:"min_sale_price"`
	CoverUrl     string `thrift:"cover_url,8" frugal:"8,default,string" json:"cover_url"`
	CreatorId    int64  `thrift:"creator_id,9" frugal:"9,default,i64" json:"creator_id"`
}

func NewProductListItem() *ProductListItem {
	return &ProductListItem{}
}

func (p *ProductListItem) InitDefault() {
}

func (p *ProductListItem) GetId() (v int64) {
	return p.Id
}

func (p *ProductListItem) GetTitle() (v string) {
	return p.Title
}

func (p *ProductListItem) GetSubTitle() (v string) {
	return p.SubTitle
}

func (p *ProductListItem) GetCategoryId() (v int64) {
	return p.CategoryId
}

func (p *ProductListItem) GetBrand() (v string) {
	return p.Brand
}

func (p *ProductListItem) GetStatus() (v int32) {
	return p.Status
}

func (p *ProductListItem) GetMinSalePrice() (v int64) {
	return p.MinSalePrice
}

func (p *ProductListItem) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *ProductListItem) GetCreatorId() (v int64) {
	return p.CreatorId
}
func (p *ProductListItem) SetId(val int64) {
	p.Id = val
}
func (p *ProductListItem) SetTitle(val string) {
	p.Title = val
}
func (p *ProductListItem) SetSubTitle(val string) {
	p.SubTitle = val
}
func (p *ProductListItem) SetCategoryId(val int64) {
	p.CategoryId = val
}
func (p *ProductListItem) SetBrand(val string) {
	p.Brand = val
}
func (p *ProductListItem) SetStatus(val int32) {
	p.Status = val
}
func (p *ProductListItem) SetMinSalePrice(val int64) {
	p.MinSalePrice = val
}
func (p *ProductListItem) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *ProductListItem) SetCreatorId(val int64) {
	p.CreatorId = val
}

func (p *ProductListItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductListItem(%+v)", *p)
}

var fieldIDToName_ProductListItem = map[int16]string{
	1: "id",
	2: "title",
	3: "sub_title",
	4: "category_id",
	5: "brand",
	6: "status",
	7: "min_sale_price",
	8: "cover_url",
	9: "creator_id",
}

type ProductSkuAttrInput struct {
	AttrName  string `thrift:"attr_name,1" frugal:"1,default,string" json:"attr_name"`
	AttrValue string `thrift:"attr_value,2" frugal:"2,default,string" json:"attr_value"`
	Sort      int32  `thrift:"sort,3" frugal:"3,default,i32" json:"sort"`
}

func NewProductSkuAttrInput() *ProductSkuAttrInput {
	return &ProductSkuAttrInput{}
}

func (p *ProductSkuAttrInput) InitDefault() {
}

func (p *ProductSkuAttrInput) GetAttrName() (v string) {
	return p.AttrName
}

func (p *ProductSkuAttrInput) GetAttrValue() (v string) {
	return p.AttrValue
}

func (p *ProductSkuAttrInput) GetSort() (v int32) {
	return p.Sort
}
func (p *ProductSkuAttrInput) SetAttrName(val string) {
	p.AttrName = val
}
func (p *ProductSkuAttrInput) SetAttrValue(val string) {
	p.AttrValue = val
}
func (p *ProductSkuAttrInput) SetSort(val int32) {
	p.Sort = val
}

func (p *ProductSkuAttrInput) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductSkuAttrInput(%+v)", *p)
}

var fieldIDToName_ProductSkuAttrInput = map[int16]string{
	1: "attr_name",
	2: "attr_value",
	3: "sort",
}

type ProductSkuInput struct {
	Id          *int64                 `thrift:"id,1,optional" frugal:"1,optional,i64" json:"id,omitempty"`
	SkuCode     string                 `thrift:"sku_code,2" frugal:"2,default,string" json:"sku_code"`
	Title       string                 `thrift:"title,3" frugal:"3,default,string" json:"title"`
	SalePrice   int64                  `thrift:"sale_price,4" frugal:"4,default,i64" json:"sale_price"`
	MarketPrice int64                  `thrift:"market_price,5" frugal:"5,default,i64" json:"market_price"`
	Status      int32                  `thrift:"status,6" frugal:"6,default,i32" json:"status"`
	CoverUrl    string                 `thrift:"cover_url,7" frugal:"7,default,string" json:"cover_url"`
	Attrs       []*ProductSkuAttrInput `thrift:"attrs,8" frugal:"8,default,list<ProductSkuAttrInput>" json:"attrs"`
}

func NewProductSkuInput() *ProductSkuInput {
	return &ProductSkuInput{}
}

func (p *ProductSkuInput) InitDefault() {
}

var ProductSkuInput_Id_DEFAULT int64

func (p *ProductSkuInput) GetId() (v int64) {
	if !p.IsSetId() {
		return ProductSkuInput_Id_DEFAULT
	}
	return *p.Id
}

func (p *ProductSkuInput) GetSkuCode() (v string) {
	return p.SkuCode
}

func (p *ProductSkuInput) GetTitle() (v string) {
	return p.Title
}

func (p *ProductSkuInput) GetSalePrice() (v int64) {
	return p.SalePrice
}

func (p *ProductSkuInput) GetMarketPrice() (v int64) {
	return p.MarketPrice
}

func (p *ProductSkuInput) GetStatus() (v int32) {
	return p.Status
}

func (p *ProductSkuInput) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *ProductSkuInput) GetAttrs() (v []*ProductSkuAttrInput) {
	return p.Attrs
}
func (p *ProductSkuInput) SetId(val *int64) {
	p.Id = val
}
func (p *ProductSkuInput) SetSkuCode(val string) {
	p.SkuCode = val
}
func (p *ProductSkuInput) SetTitle(val string) {
	p.Title = val
}
func (p *ProductSkuInput) SetSalePrice(val int64) {
	p.SalePrice = val
}
func (p *ProductSkuInput) SetMarketPrice(val int64) {
	p.MarketPrice = val
}
func (p *ProductSkuInput) SetStatus(val int32) {
	p.Status = val
}
func (p *ProductSkuInput) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *ProductSkuInput) SetAttrs(val []*ProductSkuAttrInput) {
	p.Attrs = val
}

func (p *ProductSkuInput) IsSetId() bool {
	return p.Id != nil
}

func (p *ProductSkuInput) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductSkuInput(%+v)", *p)
}

var fieldIDToName_ProductSkuInput = map[int16]string{
	1: "id",
	2: "sku_code",
	3: "title",
	4: "sale_price",
	5: "market_price",
	6: "status",
	7: "cover_url",
	8: "attrs",
}

type CreateProductRequest struct {
	Title       string             `thrift:"title,1" frugal:"1,default,string" json:"title"`
	SubTitle    string             `thrift:"sub_title,2" frugal:"2,default,string" json:"sub_title"`
	CategoryId  int64              `thrift:"category_id,3" frugal:"3,default,i64" json:"category_id"`
	Brand       string             `thrift:"brand,4" frugal:"4,default,string" json:"brand"`
	Description string             `thrift:"description,5" frugal:"5,default,string" json:"description"`
	Status      int32              `thrift:"status,6" frugal:"6,default,i32" json:"status"`
	Skus        []*ProductSkuInput `thrift:"skus,7" frugal:"7,default,list<ProductSkuInput>" json:"skus"`
	CreatorId   int64              `thrift:"creator_id,8" frugal:"8,default,i64" json:"creator_id"`
}

func NewCreateProductRequest() *CreateProductRequest {
	return &CreateProductRequest{}
}

func (p *CreateProductRequest) InitDefault() {
}

func (p *CreateProductRequest) GetTitle() (v string) {
	return p.Title
}

func (p *CreateProductRequest) GetSubTitle() (v string) {
	return p.SubTitle
}

func (p *CreateProductRequest) GetCategoryId() (v int64) {
	return p.CategoryId
}

func (p *CreateProductRequest) GetBrand() (v string) {
	return p.Brand
}

func (p *CreateProductRequest) GetDescription() (v string) {
	return p.Description
}

func (p *CreateProductRequest) GetStatus() (v int32) {
	return p.Status
}

func (p *CreateProductRequest) GetSkus() (v []*ProductSkuInput) {
	return p.Skus
}

func (p *CreateProductRequest) GetCreatorId() (v int64) {
	return p.CreatorId
}
func (p *CreateProductRequest) SetTitle(val string) {
	p.Title = val
}
func (p *CreateProductRequest) SetSubTitle(val string) {
	p.SubTitle = val
}
func (p *CreateProductRequest) SetCategoryId(val int64) {
	p.CategoryId = val
}
func (p *CreateProductRequest) SetBrand(val string) {
	p.Brand = val
}
func (p *CreateProductRequest) SetDescription(val string) {
	p.Description = val
}
func (p *CreateProductRequest) SetStatus(val int32) {
	p.Status = val
}
func (p *CreateProductRequest) SetSkus(val []*ProductSkuInput) {
	p.Skus = val
}
func (p *CreateProductRequest) SetCreatorId(val int64) {
	p.CreatorId = val
}

func (p *CreateProductRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateProductRequest(%+v)", *p)
}

var fieldIDToName_CreateProductRequest = map[int16]string{
	1: "title",
	2: "sub_title",
	3: "category_id",
	4: "brand",
	5: "description",
	6: "status",
	7: "skus",
	8: "creator_id",
}

type CreateProductSagaRequest struct {
	GlobalTxId   string             `thrift:"global_tx_id,1" frugal:"1,default,string" json:"global_tx_id"`
	BranchId     string             `thrift:"branch_id,2" frugal:"2,default,string" json:"branch_id"`
	Title        string             `thrift:"title,3" frugal:"3,default,string" json:"title"`
	SubTitle     string             `thrift:"sub_title,4" frugal:"4,default,string" json:"sub_title"`
	CategoryId   int64              `thrift:"category_id,5" frugal:"5,default,i64" json:"category_id"`
	Brand        string             `thrift:"brand,6" frugal:"6,default,string" json:"brand"`
	Description  string             `thrift:"description,7" frugal:"7,default,string" json:"description"`
	TargetStatus int32              `thrift:"target_status,8" frugal:"8,default,i32" json:"target_status"`
	Skus         []*ProductSkuInput `thrift:"skus,9" frugal:"9,default,list<ProductSkuInput>" json:"skus"`
	CreatorId    int64              `thrift:"creator_id,10" frugal:"10,default,i64" json:"creator_id"`
}

func NewCreateProductSagaRequest() *CreateProductSagaRequest {
	return &CreateProductSagaRequest{}
}

func (p *CreateProductSagaRequest) InitDefault() {
}

func (p *CreateProductSagaRequest) GetGlobalTxId() (v string) {
	return p.GlobalTxId
}

func (p *CreateProductSagaRequest) GetBranchId() (v string) {
	return p.BranchId
}

func (p *CreateProductSagaRequest) GetTitle() (v string) {
	return p.Title
}

func (p *CreateProductSagaRequest) GetSubTitle() (v string) {
	return p.SubTitle
}

func (p *CreateProductSagaRequest) GetCategoryId() (v int64) {
	return p.CategoryId
}

func (p *CreateProductSagaRequest) GetBrand() (v string) {
	return p.Brand
}

func (p *CreateProductSagaRequest) GetDescription() (v string) {
	return p.Description
}

func (p *CreateProductSagaRequest) GetTargetStatus() (v int32) {
	return p.TargetStatus
}

func (p *CreateProductSagaRequest) GetSkus() (v []*ProductSkuInput) {
	return p.Skus
}

func (p *CreateProductSagaRequest) GetCreatorId() (v int64) {
	return p.CreatorId
}
func (p *CreateProductSagaRequest) SetGlobalTxId(val string) {
	p.GlobalTxId = val
}
func (p *CreateProductSagaRequest) SetBranchId(val string) {
	p.BranchId = val
}
func (p *CreateProductSagaRequest) SetTitle(val string) {
	p.Title = val
}
func (p *CreateProductSagaRequest) SetSubTitle(val string) {
	p.SubTitle = val
}
func (p *CreateProductSagaRequest) SetCategoryId(val int64) {
	p.CategoryId = val
}
func (p *CreateProductSagaRequest) SetBrand(val string) {
	p.Brand = val
}
func (p *CreateProductSagaRequest) SetDescription(val string) {
	p.Description = val
}
func (p *CreateProductSagaRequest) SetTargetStatus(val int32) {
	p.TargetStatus = val
}
func (p *CreateProductSagaRequest) SetSkus(val []*ProductSkuInput) {
	p.Skus = val
}
func (p *CreateProductSagaRequest) SetCreatorId(val int64) {
	p.CreatorId = val
}

func (p *CreateProductSagaRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateProductSagaRequest(%+v)", *p)
}

var fieldIDToName_CreateProductSagaRequest = map[int16]string{
	1:  "global_tx_id",
	2:  "branch_id",
	3:  "title",
	4:  "sub_title",
	5:  "category_id",
	6:  "brand",
	7:  "description",
	8:  "target_status",
	9:  "skus",
	10: "creator_id",
}

type CreateProductResponse struct {
	ProductId int64              `thrift:"product_id,1" frugal:"1,default,i64" json:"product_id"`
	Skus      []*ProductSku      `thrift:"skus,2" frugal:"2,default,list<ProductSku>" json:"skus"`
	Base      *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewCreateProductResponse() *CreateProductResponse {
	return &CreateProductResponse{}
}

func (p *CreateProductResponse) InitDefault() {
}

func (p *CreateProductResponse) GetProductId() (v int64) {
	return p.ProductId
}

func (p *CreateProductResponse) GetSkus() (v []*ProductSku) {
	return p.Skus
}

var CreateProductResponse_Base_DEFAULT *base.BaseResponse

func (p *CreateProductResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return CreateProductResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *CreateProductResponse) SetProductId(val int64) {
	p.ProductId = val
}
func (p *CreateProductResponse) SetSkus(val []*ProductSku) {
	p.Skus = val
}
func (p *CreateProductResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *CreateProductResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateProductResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateProductResponse(%+v)", *p)
}

var fieldIDToName_CreateProductResponse = map[int16]string{
	1:   "product_id",
	2:   "skus",
	255: "base",
}

type CompensateCreateProductSagaRequest struct {
	GlobalTxId string `thrift:"global_tx_id,1" frugal:"1,default,string" json:"global_tx_id"`
	BranchId   string `thrift:"branch_id,2" frugal:"2,default,string" json:"branch_id"`
	ProductId  int64  `thrift:"product_id,3" frugal:"3,default,i64" json:"product_id"`
	OperatorId int64  `thrift:"operator_id,4" frugal:"4,default,i64" json:"operator_id"`
}

func NewCompensateCreateProductSagaRequest() *CompensateCreateProductSagaRequest {
	return &CompensateCreateProductSagaRequest{}
}

func (p *CompensateCreateProductSagaRequest) InitDefault() {
}

func (p *CompensateCreateProductSagaRequest) GetGlobalTxId() (v string) {
	return p.GlobalTxId
}

func (p *CompensateCreateProductSagaRequest) GetBranchId() (v string) {
	return p.BranchId
}

func (p *CompensateCreateProductSagaRequest) GetProductId() (v int64) {
	return p.ProductId
}

func (p *CompensateCreateProductSagaRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}
func (p *CompensateCreateProductSagaRequest) SetGlobalTxId(val string) {
	p.GlobalTxId = val
}
func (p *CompensateCreateProductSagaRequest) SetBranchId(val string) {
	p.BranchId = val
}
func (p *CompensateCreateProductSagaRequest) SetProductId(val int64) {
	p.ProductId = val
}
func (p *CompensateCreateProductSagaRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}

func (p *CompensateCreateProductSagaRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CompensateCreateProductSagaRequest(%+v)", *p)
}

var fieldIDToName_CompensateCreateProductSagaRequest = map[int16]string{
	1: "global_tx_id",
	2: "branch_id",
	3: "product_id",
	4: "operator_id",
}

type CompensateCreateProductSagaResponse struct {
	Base *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewCompensateCreateProductSagaResponse() *CompensateCreateProductSagaResponse {
	return &CompensateCreateProductSagaResponse{}
}

func (p *CompensateCreateProductSagaResponse) InitDefault() {
}

var CompensateCreateProductSagaResponse_Base_DEFAULT *base.BaseResponse

func (p *CompensateCreateProductSagaResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return CompensateCreateProductSagaResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *CompensateCreateProductSagaResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *CompensateCreateProductSagaResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *CompensateCreateProductSagaResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CompensateCreateProductSagaResponse(%+v)", *p)
}

var fieldIDToName_CompensateCreateProductSagaResponse = map[int16]string{
	255: "base",
}

type UpdateProductRequest struct {
	ProductId   int64              `thrift:"product_id,1" frugal:"1,default,i64" json:"product_id"`
	Title       string             `thrift:"title,2" frugal:"2,default,string" json:"title"`
	SubTitle    string             `thrift:"sub_title,3" frugal:"3,default,string" json:"sub_title"`
	CategoryId  int64              `thrift:"category_id,4" frugal:"4,default,i64" json:"category_id"`
	Brand       string             `thrift:"brand,5" frugal:"5,default,string" json:"brand"`
	Description string             `thrift:"description,6" frugal:"6,default,string" json:"description"`
	Status      int32              `thrift:"status,7" frugal:"7,default,i32" json:"status"`
	Skus        []*ProductSkuInput `thrift:"skus,8" frugal:"8,default,list<ProductSkuInput>" json:"skus"`
	OperatorId  int64              `thrift:"operator_id,9" frugal:"9,default,i64" json:"operator_id"`
}

func NewUpdateProductRequest() *UpdateProductRequest {
	return &UpdateProductRequest{}
}

func (p *UpdateProductRequest) InitDefault() {
}

func (p *UpdateProductRequest) GetProductId() (v int64) {
	return p.ProductId
}

func (p *UpdateProductRequest) GetTitle() (v string) {
	return p.Title
}

func (p *UpdateProductRequest) GetSubTitle() (v string) {
	return p.SubTitle
}

func (p *UpdateProductRequest) GetCategoryId() (v int64) {
	return p.CategoryId
}

func (p *UpdateProductRequest) GetBrand() (v string) {
	return p.Brand
}

func (p *UpdateProductRequest) GetDescription() (v string) {
	return p.Description
}

func (p *UpdateProductRequest) GetStatus() (v int32) {
	return p.Status
}

func (p *UpdateProductRequest) GetSkus() (v []*ProductSkuInput) {
	return p.Skus
}

func (p *UpdateProductRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}
func (p *UpdateProductRequest) SetProductId(val int64) {
	p.ProductId = val
}
func (p *UpdateProductRequest) SetTitle(val string) {
	p.Title = val
}
func (p *UpdateProductRequest) SetSubTitle(val string) {
	p.SubTitle = val
}
func (p *UpdateProductRequest) SetCategoryId(val int64) {
	p.CategoryId = val
}
func (p *UpdateProductRequest) SetBrand(val string) {
	p.Brand = val
}
func (p *UpdateProductRequest) SetDescription(val string) {
	p.Description = val
}
func (p *UpdateProductRequest) SetStatus(val int32) {
	p.Status = val
}
func (p *UpdateProductRequest) SetSkus(val []*ProductSkuInput) {
	p.Skus = val
}
func (p *UpdateProductRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}

func (p *UpdateProductRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateProductRequest(%+v)", *p)
}

var fieldIDToName_UpdateProductRequest = map[int16]string{
	1: "product_id",
	2: "title",
	3: "sub_title",
	4: "category_id",
	5: "brand",
	6: "description",
	7: "status",
	8: "skus",
	9: "operator_id",
}

type UpdateProductResponse struct {
	Skus []*ProductSku      `thrift:"skus,1" frugal:"1,default,list<ProductSku>" json:"skus"`
	Base *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewUpdateProductResponse() *UpdateProductResponse {
	return &UpdateProductResponse{}
}

func (p *UpdateProductResponse) InitDefault() {
}

func (p *UpdateProductResponse) GetSkus() (v []*ProductSku) {
	return p.Skus
}

var UpdateProductResponse_Base_DEFAULT *base.BaseResponse

func (p *UpdateProductResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return UpdateProductResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *UpdateProductResponse) SetSkus(val []*ProductSku) {
	p.Skus = val
}
func (p *UpdateProductResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *UpdateProductResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateProductResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateProductResponse(%+v)", *p)
}

var fieldIDToName_UpdateProductResponse = map[int16]string{
	1:   "skus",
	255: "base",
}

type ChangeProductStatusRequest struct {
	ProductId  int64 `thrift:"product_id,1" frugal:"1,default,i64" json:"product_id"`
	Status     int32 `thrift:"status,2" frugal:"2,default,i32" json:"status"`
	OperatorId int64 `thrift:"operator_id,3" frugal:"3,default,i64" json:"operator_id"`
}

func NewChangeProductStatusRequest() *ChangeProductStatusRequest {
	return &ChangeProductStatusRequest{}
}

func (p *ChangeProductStatusRequest) InitDefault() {
}

func (p *ChangeProductStatusRequest) GetProductId() (v int64) {
	return p.ProductId
}

func (p *ChangeProductStatusRequest) GetStatus() (v int32) {
	return p.Status
}

func (p *ChangeProductStatusRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}
func (p *ChangeProductStatusRequest) SetProductId(val int64) {
	p.ProductId = val
}
func (p *ChangeProductStatusRequest) SetStatus(val int32) {
	p.Status = val
}
func (p *ChangeProductStatusRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}

func (p *ChangeProductStatusRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeProductStatusRequest(%+v)", *p)
}

var fieldIDToName_ChangeProductStatusRequest = map[int16]string{
	1: "product_id",
	2: "status",
	3: "operator_id",
}

type ChangeProductStatusResponse struct {
	Base *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewChangeProductStatusResponse() *ChangeProductStatusResponse {
	return &ChangeProductStatusResponse{}
}

func (p *ChangeProductStatusResponse) InitDefault() {
}

var ChangeProductStatusResponse_Base_DEFAULT *base.BaseResponse

func (p *ChangeProductStatusResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return ChangeProductStatusResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *ChangeProductStatusResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *ChangeProductStatusResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *ChangeProductStatusResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeProductStatusResponse(%+v)", *p)
}

var fieldIDToName_ChangeProductStatusResponse = map[int16]string{
	255: "base",
}

type GetProductDetailRequest struct {
	ProductId int64 `thrift:"product_id,1" frugal:"1,default,i64" json:"product_id"`
}

func NewGetProductDetailRequest() *GetProductDetailRequest {
	return &GetProductDetailRequest{}
}

func (p *GetProductDetailRequest) InitDefault() {
}

func (p *GetProductDetailRequest) GetProductId() (v int64) {
	return p.ProductId
}
func (p *GetProductDetailRequest) SetProductId(val int64) {
	p.ProductId = val
}

func (p *GetProductDetailRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProductDetailRequest(%+v)", *p)
}

var fieldIDToName_GetProductDetailRequest = map[int16]string{
	1: "product_id",
}

type GetProductDetailResponse struct {
	Product *Product           `thrift:"product,1" frugal:"1,default,Product" json:"product"`
	Base    *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewGetProductDetailResponse() *GetProductDetailResponse {
	return &GetProductDetailResponse{}
}

func (p *GetProductDetailResponse) InitDefault() {
}

var GetProductDetailResponse_Product_DEFAULT *Product

func (p *GetProductDetailResponse) GetProduct() (v *Product) {
	if !p.IsSetProduct() {
		return GetProductDetailResponse_Product_DEFAULT
	}
	return p.Product
}

var GetProductDetailResponse_Base_DEFAULT *base.BaseResponse

func (p *GetProductDetailResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return GetProductDetailResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *GetProductDetailResponse) SetProduct(val *Product) {
	p.Product = val
}
func (p *GetProductDetailResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *GetProductDetailResponse) IsSetProduct() bool {
	return p.Product != nil
}

func (p *GetProductDetailResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetProductDetailResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProductDetailResponse(%+v)", *p)
}

var fieldIDToName_GetProductDetailResponse = map[int16]string{
	1:   "product",
	255: "base",
}

type ListProductsRequest struct {
	Page       int32   `thrift:"page,1" frugal:"1,default,i32" json:"page"`
	PageSize   int32   `thrift:"page_size,2" frugal:"2,default,i32" json:"page_size"`
	Status     *int32  `thrift:"status,3,optional" frugal:"3,optional,i32" json:"status,omitempty"`
	CategoryId *int64  `thrift:"category_id,4,optional" frugal:"4,optional,i64" json:"category_id,omitempty"`
	Keyword    *string `thrift:"keyword,5,optional" frugal:"5,optional,string" json:"keyword,omitempty"`
	CreatorId  *int64  `thrift:"creator_id,6,optional" frugal:"6,optional,i64" json:"creator_id,omitempty"`
}

func NewListProductsRequest() *ListProductsRequest {
	return &ListProductsRequest{}
}

func (p *ListProductsRequest) InitDefault() {
}

func (p *ListProductsRequest) GetPage() (v int32) {
	return p.Page
}

func (p *ListProductsRequest) GetPageSize() (v int32) {
	return p.PageSize
}

var ListProductsRequest_Status_DEFAULT int32

func (p *ListProductsRequest) GetStatus() (v int32) {
	if !p.IsSetStatus() {
		return ListProductsRequest_Status_DEFAULT
	}
	return *p.Status
}

var ListProductsRequest_CategoryId_DEFAULT int64

func (p *ListProductsRequest) GetCategoryId() (v int64) {
	if !p.IsSetCategoryId() {
		return ListProductsRequest_CategoryId_DEFAULT
	}
	return *p.CategoryId
}

var ListProductsRequest_Keyword_DEFAULT string

func (p *ListProductsRequest) GetKeyword() (v string) {
	if !p.IsSetKeyword() {
		return ListProductsRequest_Keyword_DEFAULT
	}
	return *p.Keyword
}

var ListProductsRequest_CreatorId_DEFAULT int64

func (p *ListProductsRequest) GetCreatorId() (v int64) {
	if !p.IsSetCreatorId() {
		return ListProductsRequest_CreatorId_DEFAULT
	}
	return *p.CreatorId
}
func (p *ListProductsRequest) SetPage(val int32) {
	p.Page = val
}
func (p *ListProductsRequest) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *ListProductsRequest) SetStatus(val *int32) {
	p.Status = val
}
func (p *ListProductsRequest) SetCategoryId(val *int64) {
	p.CategoryId = val
}
func (p *ListProductsRequest) SetKeyword(val *string) {
	p.Keyword = val
}
func (p *ListProductsRequest) SetCreatorId(val *int64) {
	p.CreatorId = val
}

func (p *ListProductsRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *ListProductsRequest) IsSetCategoryId() bool {
	return p.CategoryId != nil
}

func (p *ListProductsRequest) IsSetKeyword() bool {
	return p.Keyword != nil
}

func (p *ListProductsRequest) IsSetCreatorId() bool {
	return p.CreatorId != nil
}

func (p *ListProductsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListProductsRequest(%+v)", *p)
}

var fieldIDToName_ListProductsRequest = map[int16]string{
	1: "page",
	2: "page_size",
	3: "status",
	4: "category_id",
	5: "keyword",
	6: "creator_id",
}

type ListProductsResponse struct {
	Products []*ProductListItem `thrift:"products,1" frugal:"1,default,list<ProductListItem>" json:"products"`
	Total    int64              `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	Base     *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewListProductsResponse() *ListProductsResponse {
	return &ListProductsResponse{}
}

func (p *ListProductsResponse) InitDefault() {
}

func (p *ListProductsResponse) GetProducts() (v []*ProductListItem) {
	return p.Products
}

func (p *ListProductsResponse) GetTotal() (v int64) {
	return p.Total
}

var ListProductsResponse_Base_DEFAULT *base.BaseResponse

func (p *ListProductsResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return ListProductsResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *ListProductsResponse) SetProducts(val []*ProductListItem) {
	p.Products = val
}
func (p *ListProductsResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *ListProductsResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *ListProductsResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListProductsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListProductsResponse(%+v)", *p)
}

var fieldIDToName_ListProductsResponse = map[int16]string{
	1:   "products",
	2:   "total",
	255: "base",
}

type BatchGetSkuRequest struct {
	SkuIds []int64 `thrift:"sku_ids,1" frugal:"1,default,list<i64>" json:"sku_ids"`
}

func NewBatchGetSkuRequest() *BatchGetSkuRequest {
	return &BatchGetSkuRequest{}
}

func (p *BatchGetSkuRequest) InitDefault() {
}

func (p *BatchGetSkuRequest) GetSkuIds() (v []int64) {
	return p.SkuIds
}
func (p *BatchGetSkuRequest) SetSkuIds(val []int64) {
	p.SkuIds = val
}

func (p *BatchGetSkuRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchGetSkuRequest(%+v)", *p)
}

var fieldIDToName_BatchGetSkuRequest = map[int16]string{
	1: "sku_ids",
}

type BatchGetSkuResponse struct {
	Skus []*ProductSku      `thrift:"skus,1" frugal:"1,default,list<ProductSku>" json:"skus"`
	Base *base.BaseResponse `thrift:"base,255" frugal:"255,default,base.BaseResponse" json:"base"`
}

func NewBatchGetSkuResponse() *BatchGetSkuResponse {
	return &BatchGetSkuResponse{}
}

func (p *BatchGetSkuResponse) InitDefault() {
}

func (p *BatchGetSkuResponse) GetSkus() (v []*ProductSku) {
	return p.Skus
}

var BatchGetSkuResponse_Base_DEFAULT *base.BaseResponse

func (p *BatchGetSkuResponse) GetBase() (v *base.BaseResponse) {
	if !p.IsSetBase() {
		return BatchGetSkuResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *BatchGetSkuResponse) SetSkus(val []*ProductSku) {
	p.Skus = val
}
func (p *BatchGetSkuResponse) SetBase(val *base.BaseResponse) {
	p.Base = val
}

func (p *BatchGetSkuResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *BatchGetSkuResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchGetSkuResponse(%+v)", *p)
}

var fieldIDToName_BatchGetSkuResponse = map[int16]string{
	1:   "skus",
	255: "base",
}

type ProductService interface {
	CreateProduct(ctx context.Context, request *CreateProductRequest) (r *CreateProductResponse, err error)

	CreateProductSaga(ctx context.Context, request *CreateProductSagaRequest) (r *CreateProductResponse, err error)

	CompensateCreateProductSaga(ctx context.Context, request *CompensateCreateProductSagaRequest) (r *CompensateCreateProductSagaResponse, err error)

	UpdateProduct(ctx context.Context, request *UpdateProductRequest) (r *UpdateProductResponse, err error)

	ChangeProductStatus(ctx context.Context, request *ChangeProductStatusRequest) (r *ChangeProductStatusResponse, err error)

	GetProductDetail(ctx context.Context, request *GetProductDetailRequest) (r *GetProductDetailResponse, err error)

	ListProducts(ctx context.Context, request *ListProductsRequest) (r *ListProductsResponse, err error)

	BatchGetSku(ctx context.Context, request *BatchGetSkuRequest) (r *BatchGetSkuResponse, err error)
}

type ProductServiceCreateProductArgs struct {
	Request *CreateProductRequest `thrift:"request,1" frugal:"1,default,CreateProductRequest" json:"request"`
}

func NewProductServiceCreateProductArgs() *ProductServiceCreateProductArgs {
	return &ProductServiceCreateProductArgs{}
}

func (p *ProductServiceCreateProductArgs) InitDefault() {
}

var ProductServiceCreateProductArgs_Request_DEFAULT *CreateProductRequest

func (p *ProductServiceCreateProductArgs) GetRequest() (v *CreateProductRequest) {
	if !p.IsSetRequest() {
		return ProductServiceCreateProductArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *ProductServiceCreateProductArgs) SetRequest(val *CreateProductRequest) {
	p.Request = val
}

func (p *ProductServiceCreateProductArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ProductServiceCreateProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceCreateProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceCreateProductArgs = map[int16]string{
	1: "request",
}

type ProductServiceCreateProductResult struct {
	Success *CreateProductResponse `thrift:"success,0,optional" frugal:"0,optional,CreateProductResponse" json:"success,omitempty"`
}

func NewProductServiceCreateProductResult() *ProductServiceCreateProductResult {
	return &ProductServiceCreateProductResult{}
}

func (p *ProductServiceCreateProductResult) InitDefault() {
}

var ProductServiceCreateProductResult_Success_DEFAULT *CreateProductResponse

func (p *ProductServiceCreateProductResult) GetSuccess() (v *CreateProductResponse) {
	if !p.IsSetSuccess() {
		return ProductServiceCreateProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceCreateProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateProductResponse)
}

func (p *ProductServiceCreateProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceCreateProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceCreateProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceCreateProductResult = map[int16]string{
	0: "success",
}

type ProductServiceCreateProductSagaArgs struct {
	Request *CreateProductSagaRequest `thrift:"request,1" frugal:"1,default,CreateProductSagaRequest" json:"request"`
}

func NewProductServiceCreateProductSagaArgs() *ProductServiceCreateProductSagaArgs {
	return &ProductServiceCreateProductSagaArgs{}
}

func (p *ProductServiceCreateProductSagaArgs) InitDefault() {
}

var ProductServiceCreateProductSagaArgs_Request_DEFAULT *CreateProductSagaRequest

func (p *ProductServiceCreateProductSagaArgs) GetRequest() (v *CreateProductSagaRequest) {
	if !p.IsSetRequest() {
		return ProductServiceCreateProductSagaArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *ProductServiceCreateProductSagaArgs) SetRequest(val *CreateProductSagaRequest) {
	p.Request = val
}

func (p *ProductServiceCreateProductSagaArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ProductServiceCreateProductSagaArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceCreateProductSagaArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceCreateProductSagaArgs = map[int16]string{
	1: "request",
}

type ProductServiceCreateProductSagaResult struct {
	Success *CreateProductResponse `thrift:"success,0,optional" frugal:"0,optional,CreateProductResponse" json:"success,omitempty"`
}

func NewProductServiceCreateProductSagaResult() *ProductServiceCreateProductSagaResult {
	return &ProductServiceCreateProductSagaResult{}
}

func (p *ProductServiceCreateProductSagaResult) InitDefault() {
}

var ProductServiceCreateProductSagaResult_Success_DEFAULT *CreateProductResponse

func (p *ProductServiceCreateProductSagaResult) GetSuccess() (v *CreateProductResponse) {
	if !p.IsSetSuccess() {
		return ProductServiceCreateProductSagaResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceCreateProductSagaResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateProductResponse)
}

func (p *ProductServiceCreateProductSagaResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceCreateProductSagaResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceCreateProductSagaResult(%+v)", *p)
}

var fieldIDToName_ProductServiceCreateProductSagaResult = map[int16]string{
	0: "success",
}

type ProductServiceCompensateCreateProductSagaArgs struct {
	Request *CompensateCreateProductSagaRequest `thrift:"request,1" frugal:"1,default,CompensateCreateProductSagaRequest" json:"request"`
}

func NewProductServiceCompensateCreateProductSagaArgs() *ProductServiceCompensateCreateProductSagaArgs {
	return &ProductServiceCompensateCreateProductSagaArgs{}
}

func (p *ProductServiceCompensateCreateProductSagaArgs) InitDefault() {
}

var ProductServiceCompensateCreateProductSagaArgs_Request_DEFAULT *CompensateCreateProductSagaRequest

func (p *ProductServiceCompensateCreateProductSagaArgs) GetRequest() (v *CompensateCreateProductSagaRequest) {
	if !p.IsSetRequest() {
		return ProductServiceCompensateCreateProductSagaArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *ProductServiceCompensateCreateProductSagaArgs) SetRequest(val *CompensateCreateProductSagaRequest) {
	p.Request = val
}

func (p *ProductServiceCompensateCreateProductSagaArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ProductServiceCompensateCreateProductSagaArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceCompensateCreateProductSagaArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceCompensateCreateProductSagaArgs = map[int16]string{
	1: "request",
}

type ProductServiceCompensateCreateProductSagaResult struct {
	Success *CompensateCreateProductSagaResponse `thrift:"success,0,optional" frugal:"0,optional,CompensateCreateProductSagaResponse" json:"success,omitempty"`
}

func NewProductServiceCompensateCreateProductSagaResult() *ProductServiceCompensateCreateProductSagaResult {
	return &ProductServiceCompensateCreateProductSagaResult{}
}

func (p *ProductServiceCompensateCreateProductSagaResult) InitDefault() {
}

var ProductServiceCompensateCreateProductSagaResult_Success_DEFAULT *CompensateCreateProductSagaResponse

func (p *ProductServiceCompensateCreateProductSagaResult) GetSuccess() (v *CompensateCreateProductSagaResponse) {
	if !p.IsSetSuccess() {
		return ProductServiceCompensateCreateProductSagaResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceCompensateCreateProductSagaResult) SetSuccess(x interface{}) {
	p.Success = x.(*CompensateCreateProductSagaResponse)
}

func (p *ProductServiceCompensateCreateProductSagaResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceCompensateCreateProductSagaResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceCompensateCreateProductSagaResult(%+v)", *p)
}

var fieldIDToName_ProductServiceCompensateCreateProductSagaResult = map[int16]string{
	0: "success",
}

type ProductServiceUpdateProductArgs struct {
	Request *UpdateProductRequest `thrift:"request,1" frugal:"1,default,UpdateProductRequest" json:"request"`
}

func NewProductServiceUpdateProductArgs() *ProductServiceUpdateProductArgs {
	return &ProductServiceUpdateProductArgs{}
}

func (p *ProductServiceUpdateProductArgs) InitDefault() {
}

var ProductServiceUpdateProductArgs_Request_DEFAULT *UpdateProductRequest

func (p *ProductServiceUpdateProductArgs) GetRequest() (v *UpdateProductRequest) {
	if !p.IsSetRequest() {
		return ProductServiceUpdateProductArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *ProductServiceUpdateProductArgs) SetRequest(val *UpdateProductRequest) {
	p.Request = val
}

func (p *ProductServiceUpdateProductArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ProductServiceUpdateProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceUpdateProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceUpdateProductArgs = map[int16]string{
	1: "request",
}

type ProductServiceUpdateProductResult struct {
	Success *UpdateProductResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateProductResponse" json:"success,omitempty"`
}

func NewProductServiceUpdateProductResult() *ProductServiceUpdateProductResult {
	return &ProductServiceUpdateProductResult{}
}

func (p *ProductServiceUpdateProductResult) InitDefault() {
}

var ProductServiceUpdateProductResult_Success_DEFAULT *UpdateProductResponse

func (p *ProductServiceUpdateProductResult) GetSuccess() (v *UpdateProductResponse) {
	if !p.IsSetSuccess() {
		return ProductServiceUpdateProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceUpdateProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateProductResponse)
}

func (p *ProductServiceUpdateProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceUpdateProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceUpdateProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceUpdateProductResult = map[int16]string{
	0: "success",
}

type ProductServiceChangeProductStatusArgs struct {
	Request *ChangeProductStatusRequest `thrift:"request,1" frugal:"1,default,ChangeProductStatusRequest" json:"request"`
}

func NewProductServiceChangeProductStatusArgs() *ProductServiceChangeProductStatusArgs {
	return &ProductServiceChangeProductStatusArgs{}
}

func (p *ProductServiceChangeProductStatusArgs) InitDefault() {
}

var ProductServiceChangeProductStatusArgs_Request_DEFAULT *ChangeProductStatusRequest

func (p *ProductServiceChangeProductStatusArgs) GetRequest() (v *ChangeProductStatusRequest) {
	if !p.IsSetRequest() {
		return ProductServiceChangeProductStatusArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *ProductServiceChangeProductStatusArgs) SetRequest(val *ChangeProductStatusRequest) {
	p.Request = val
}

func (p *ProductServiceChangeProductStatusArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ProductServiceChangeProductStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceChangeProductStatusArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceChangeProductStatusArgs = map[int16]string{
	1: "request",
}

type ProductServiceChangeProductStatusResult struct {
	Success *ChangeProductStatusResponse `thrift:"success,0,optional" frugal:"0,optional,ChangeProductStatusResponse" json:"success,omitempty"`
}

func NewProductServiceChangeProductStatusResult() *ProductServiceChangeProductStatusResult {
	return &ProductServiceChangeProductStatusResult{}
}

func (p *ProductServiceChangeProductStatusResult) InitDefault() {
}

var ProductServiceChangeProductStatusResult_Success_DEFAULT *ChangeProductStatusResponse

func (p *ProductServiceChangeProductStatusResult) GetSuccess() (v *ChangeProductStatusResponse) {
	if !p.IsSetSuccess() {
		return ProductServiceChangeProductStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceChangeProductStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChangeProductStatusResponse)
}

func (p *ProductServiceChangeProductStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceChangeProductStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceChangeProductStatusResult(%+v)", *p)
}

var fieldIDToName_ProductServiceChangeProductStatusResult = map[int16]string{
	0: "success",
}

type ProductServiceGetProductDetailArgs struct {
	Request *GetProductDetailRequest `thrift:"request,1" frugal:"1,default,GetProductDetailRequest" json:"request"`
}

func NewProductServiceGetProductDetailArgs() *ProductServiceGetProductDetailArgs {
	return &ProductServiceGetProductDetailArgs{}
}

func (p *ProductServiceGetProductDetailArgs) InitDefault() {
}

var ProductServiceGetProductDetailArgs_Request_DEFAULT *GetProductDetailRequest

func (p *ProductServiceGetProductDetailArgs) GetRequest() (v *GetProductDetailRequest) {
	if !p.IsSetRequest() {
		return ProductServiceGetProductDetailArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *ProductServiceGetProductDetailArgs) SetRequest(val *GetProductDetailRequest) {
	p.Request = val
}

func (p *ProductServiceGetProductDetailArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ProductServiceGetProductDetailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductDetailArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductDetailArgs = map[int16]string{
	1: "request",
}

type ProductServiceGetProductDetailResult struct {
	Success *GetProductDetailResponse `thrift:"success,0,optional" frugal:"0,optional,GetProductDetailResponse" json:"success,omitempty"`
}

func NewProductServiceGetProductDetailResult() *ProductServiceGetProductDetailResult {
	return &ProductServiceGetProductDetailResult{}
}

func (p *ProductServiceGetProductDetailResult) InitDefault() {
}

var ProductServiceGetProductDetailResult_Success_DEFAULT *GetProductDetailResponse

func (p *ProductServiceGetProductDetailResult) GetSuccess() (v *GetProductDetailResponse) {
	if !p.IsSetSuccess() {
		return ProductServiceGetProductDetailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceGetProductDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetProductDetailResponse)
}

func (p *ProductServiceGetProductDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceGetProductDetailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductDetailResult(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductDetailResult = map[int16]string{
	0: "success",
}

type ProductServiceListProductsArgs struct {
	Request *ListProductsRequest `thrift:"request,1" frugal:"1,default,ListProductsRequest" json:"request"`
}

func NewProductServiceListProductsArgs() *ProductServiceListProductsArgs {
	return &ProductServiceListProductsArgs{}
}

func (p *ProductServiceListProductsArgs) InitDefault() {
}

var ProductServiceListProductsArgs_Request_DEFAULT *ListProductsRequest

func (p *ProductServiceListProductsArgs) GetRequest() (v *ListProductsRequest) {
	if !p.IsSetRequest() {
		return ProductServiceListProductsArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *ProductServiceListProductsArgs) SetRequest(val *ListProductsRequest) {
	p.Request = val
}

func (p *ProductServiceListProductsArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ProductServiceListProductsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceListProductsArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceListProductsArgs = map[int16]string{
	1: "request",
}

type ProductServiceListProductsResult struct {
	Success *ListProductsResponse `thrift:"success,0,optional" frugal:"0,optional,ListProductsResponse" json:"success,omitempty"`
}

func NewProductServiceListProductsResult() *ProductServiceListProductsResult {
	return &ProductServiceListProductsResult{}
}

func (p *ProductServiceListProductsResult) InitDefault() {
}

var ProductServiceListProductsResult_Success_DEFAULT *ListProductsResponse

func (p *ProductServiceListProductsResult) GetSuccess() (v *ListProductsResponse) {
	if !p.IsSetSuccess() {
		return ProductServiceListProductsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceListProductsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListProductsResponse)
}

func (p *ProductServiceListProductsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceListProductsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceListProductsResult(%+v)", *p)
}

var fieldIDToName_ProductServiceListProductsResult = map[int16]string{
	0: "success",
}

type ProductServiceBatchGetSkuArgs struct {
	Request *BatchGetSkuRequest `thrift:"request,1" frugal:"1,default,BatchGetSkuRequest" json:"request"`
}

func NewProductServiceBatchGetSkuArgs() *ProductServiceBatchGetSkuArgs {
	return &ProductServiceBatchGetSkuArgs{}
}

func (p *ProductServiceBatchGetSkuArgs) InitDefault() {
}

var ProductServiceBatchGetSkuArgs_Request_DEFAULT *BatchGetSkuRequest

func (p *ProductServiceBatchGetSkuArgs) GetRequest() (v *BatchGetSkuRequest) {
	if !p.IsSetRequest() {
		return ProductServiceBatchGetSkuArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *ProductServiceBatchGetSkuArgs) SetRequest(val *BatchGetSkuRequest) {
	p.Request = val
}

func (p *ProductServiceBatchGetSkuArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ProductServiceBatchGetSkuArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceBatchGetSkuArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceBatchGetSkuArgs = map[int16]string{
	1: "request",
}

type ProductServiceBatchGetSkuResult struct {
	Success *BatchGetSkuResponse `thrift:"success,0,optional" frugal:"0,optional,BatchGetSkuResponse" json:"success,omitempty"`
}

func NewProductServiceBatchGetSkuResult() *ProductServiceBatchGetSkuResult {
	return &ProductServiceBatchGetSkuResult{}
}

func (p *ProductServiceBatchGetSkuResult) InitDefault() {
}

var ProductServiceBatchGetSkuResult_Success_DEFAULT *BatchGetSkuResponse

func (p *ProductServiceBatchGetSkuResult) GetSuccess() (v *BatchGetSkuResponse) {
	if !p.IsSetSuccess() {
		return ProductServiceBatchGetSkuResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceBatchGetSkuResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchGetSkuResponse)
}

func (p *ProductServiceBatchGetSkuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceBatchGetSkuResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceBatchGetSkuResult(%+v)", *p)
}

var fieldIDToName_ProductServiceBatchGetSkuResult = map[int16]string{
	0: "success",
}
