#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT_DIR"

export APP_ENV="${APP_ENV:-dev}"
export LOG_LEVEL="${LOG_LEVEL:-info}"
export LOG_DIR="${LOG_DIR:-logs}"
export OTEL_EXPORTER_OTLP_ENDPOINT="${OTEL_EXPORTER_OTLP_ENDPOINT:-localhost:4319}"
export CART_METRICS_ADDR="${CART_METRICS_ADDR:-:9094}"
export CART_SERVICE_CONFIG="${CART_SERVICE_CONFIG:-services/cart-service/config/cart-service.local.yaml}"
export CART_SERVICE_CONFIG_SOURCE="${CART_SERVICE_CONFIG_SOURCE:-file}"
export CART_RPC_SERVICE="${CART_RPC_SERVICE:-meshcart.cart}"
export CART_SERVICE_ADDR="${CART_SERVICE_ADDR:-127.0.0.1:8890}"
export CART_SERVICE_REGISTRY="${CART_SERVICE_REGISTRY:-consul}"
export CONSUL_ADDR="${CONSUL_ADDR:-127.0.0.1:8500}"
export CART_SERVICE_CONSUL_TCP_CHECK="${CART_SERVICE_CONSUL_TCP_CHECK:-false}"
export CART_SERVICE_SHUTDOWN_TIMEOUT_MS="${CART_SERVICE_SHUTDOWN_TIMEOUT_MS:-5000}"
export CART_SERVICE_PREFLIGHT_TIMEOUT_MS="${CART_SERVICE_PREFLIGHT_TIMEOUT_MS:-1500}"
export CART_SERVICE_DRAIN_TIMEOUT_MS="${CART_SERVICE_DRAIN_TIMEOUT_MS:-500}"

if [[ ! -f "$CART_SERVICE_CONFIG" ]]; then
  echo "[ERROR] config file not found: $CART_SERVICE_CONFIG" >&2
  exit 1
fi

echo "[INFO] starting cart-service"
echo "[INFO] APP_ENV=$APP_ENV LOG_LEVEL=$LOG_LEVEL LOG_DIR=$LOG_DIR OTEL_EXPORTER_OTLP_ENDPOINT=$OTEL_EXPORTER_OTLP_ENDPOINT"
echo "[INFO] CART_METRICS_ADDR=$CART_METRICS_ADDR CART_SERVICE_CONFIG=$CART_SERVICE_CONFIG CART_SERVICE_CONFIG_SOURCE=$CART_SERVICE_CONFIG_SOURCE"
echo "[INFO] CART_RPC_SERVICE=$CART_RPC_SERVICE CART_SERVICE_ADDR=$CART_SERVICE_ADDR CART_SERVICE_REGISTRY=$CART_SERVICE_REGISTRY CONSUL_ADDR=$CONSUL_ADDR CART_SERVICE_CONSUL_TCP_CHECK=$CART_SERVICE_CONSUL_TCP_CHECK"
echo "[INFO] CART_SERVICE_SHUTDOWN_TIMEOUT_MS=$CART_SERVICE_SHUTDOWN_TIMEOUT_MS CART_SERVICE_PREFLIGHT_TIMEOUT_MS=$CART_SERVICE_PREFLIGHT_TIMEOUT_MS CART_SERVICE_DRAIN_TIMEOUT_MS=$CART_SERVICE_DRAIN_TIMEOUT_MS healthz=http://127.0.0.1${CART_METRICS_ADDR}/healthz readyz=http://127.0.0.1${CART_METRICS_ADDR}/readyz metrics=http://127.0.0.1${CART_METRICS_ADDR}/metrics"

exec go run ./services/cart-service/rpc
