// Code generated by Kitex v0.16.1. DO NOT EDIT.

package productservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	product "meshcart/kitex_gen/meshcart/product"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateProduct(ctx context.Context, request *product.CreateProductRequest, callOptions ...callopt.Option) (r *product.CreateProductResponse, err error)
	CreateProductSaga(ctx context.Context, request *product.CreateProductSagaRequest, callOptions ...callopt.Option) (r *product.CreateProductResponse, err error)
	CompensateCreateProductSaga(ctx context.Context, request *product.CompensateCreateProductSagaRequest, callOptions ...callopt.Option) (r *product.CompensateCreateProductSagaResponse, err error)
	UpdateProduct(ctx context.Context, request *product.UpdateProductRequest, callOptions ...callopt.Option) (r *product.UpdateProductResponse, err error)
	ChangeProductStatus(ctx context.Context, request *product.ChangeProductStatusRequest, callOptions ...callopt.Option) (r *product.ChangeProductStatusResponse, err error)
	GetProductDetail(ctx context.Context, request *product.GetProductDetailRequest, callOptions ...callopt.Option) (r *product.GetProductDetailResponse, err error)
	ListProducts(ctx context.Context, request *product.ListProductsRequest, callOptions ...callopt.Option) (r *product.ListProductsResponse, err error)
	BatchGetSku(ctx context.Context, request *product.BatchGetSkuRequest, callOptions ...callopt.Option) (r *product.BatchGetSkuResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kProductServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kProductServiceClient struct {
	*kClient
}

func (p *kProductServiceClient) CreateProduct(ctx context.Context, request *product.CreateProductRequest, callOptions ...callopt.Option) (r *product.CreateProductResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateProduct(ctx, request)
}

func (p *kProductServiceClient) CreateProductSaga(ctx context.Context, request *product.CreateProductSagaRequest, callOptions ...callopt.Option) (r *product.CreateProductResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateProductSaga(ctx, request)
}

func (p *kProductServiceClient) CompensateCreateProductSaga(ctx context.Context, request *product.CompensateCreateProductSagaRequest, callOptions ...callopt.Option) (r *product.CompensateCreateProductSagaResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CompensateCreateProductSaga(ctx, request)
}

func (p *kProductServiceClient) UpdateProduct(ctx context.Context, request *product.UpdateProductRequest, callOptions ...callopt.Option) (r *product.UpdateProductResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProduct(ctx, request)
}

func (p *kProductServiceClient) ChangeProductStatus(ctx context.Context, request *product.ChangeProductStatusRequest, callOptions ...callopt.Option) (r *product.ChangeProductStatusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeProductStatus(ctx, request)
}

func (p *kProductServiceClient) GetProductDetail(ctx context.Context, request *product.GetProductDetailRequest, callOptions ...callopt.Option) (r *product.GetProductDetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProductDetail(ctx, request)
}

func (p *kProductServiceClient) ListProducts(ctx context.Context, request *product.ListProductsRequest, callOptions ...callopt.Option) (r *product.ListProductsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListProducts(ctx, request)
}

func (p *kProductServiceClient) BatchGetSku(ctx context.Context, request *product.BatchGetSkuRequest, callOptions ...callopt.Option) (r *product.BatchGetSkuResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetSku(ctx, request)
}
