mysql:
  address: "127.0.0.1:3306"
  username: "root"
  password: "2FaJkFtkMkC3yeBK"
  database: "meshcart_inventory"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"

migration:
  enabled: true
  source: "file://services/inventory-service/migrations"

snowflake:
  node: 4

timeout:
  db_query_ms: 1500
