// Code generated by Kitex v0.16.1. DO NOT EDIT.

package paymentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	payment "meshcart/kitex_gen/meshcart/payment"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreatePayment(ctx context.Context, request *payment.CreatePaymentRequest, callOptions ...callopt.Option) (r *payment.CreatePaymentResponse, err error)
	GetPayment(ctx context.Context, request *payment.GetPaymentRequest, callOptions ...callopt.Option) (r *payment.GetPaymentResponse, err error)
	ListPaymentsByOrder(ctx context.Context, request *payment.ListPaymentsByOrderRequest, callOptions ...callopt.Option) (r *payment.ListPaymentsByOrderResponse, err error)
	ConfirmPaymentSuccess(ctx context.Context, request *payment.ConfirmPaymentSuccessRequest, callOptions ...callopt.Option) (r *payment.ConfirmPaymentSuccessResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPaymentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPaymentServiceClient struct {
	*kClient
}

func (p *kPaymentServiceClient) CreatePayment(ctx context.Context, request *payment.CreatePaymentRequest, callOptions ...callopt.Option) (r *payment.CreatePaymentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePayment(ctx, request)
}

func (p *kPaymentServiceClient) GetPayment(ctx context.Context, request *payment.GetPaymentRequest, callOptions ...callopt.Option) (r *payment.GetPaymentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPayment(ctx, request)
}

func (p *kPaymentServiceClient) ListPaymentsByOrder(ctx context.Context, request *payment.ListPaymentsByOrderRequest, callOptions ...callopt.Option) (r *payment.ListPaymentsByOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPaymentsByOrder(ctx, request)
}

func (p *kPaymentServiceClient) ConfirmPaymentSuccess(ctx context.Context, request *payment.ConfirmPaymentSuccessRequest, callOptions ...callopt.Option) (r *payment.ConfirmPaymentSuccessResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfirmPaymentSuccess(ctx, request)
}
