// Code generated by Kitex v0.16.1. DO NOT EDIT.

package paymentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	payment "meshcart/kitex_gen/meshcart/payment"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"createPayment": kitex.NewMethodInfo(
		createPaymentHandler,
		newPaymentServiceCreatePaymentArgs,
		newPaymentServiceCreatePaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"getPayment": kitex.NewMethodInfo(
		getPaymentHandler,
		newPaymentServiceGetPaymentArgs,
		newPaymentServiceGetPaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"listPaymentsByOrder": kitex.NewMethodInfo(
		listPaymentsByOrderHandler,
		newPaymentServiceListPaymentsByOrderArgs,
		newPaymentServiceListPaymentsByOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"confirmPaymentSuccess": kitex.NewMethodInfo(
		confirmPaymentSuccessHandler,
		newPaymentServiceConfirmPaymentSuccessArgs,
		newPaymentServiceConfirmPaymentSuccessResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	paymentServiceServiceInfo                = NewServiceInfo()
	paymentServiceServiceInfoForClient       = NewServiceInfoForClient()
	paymentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return paymentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PaymentService"
	handlerType := (*payment.PaymentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "payment",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createPaymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceCreatePaymentArgs)
	realResult := result.(*payment.PaymentServiceCreatePaymentResult)
	success, err := handler.(payment.PaymentService).CreatePayment(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceCreatePaymentArgs() interface{} {
	return payment.NewPaymentServiceCreatePaymentArgs()
}

func newPaymentServiceCreatePaymentResult() interface{} {
	return payment.NewPaymentServiceCreatePaymentResult()
}

func getPaymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceGetPaymentArgs)
	realResult := result.(*payment.PaymentServiceGetPaymentResult)
	success, err := handler.(payment.PaymentService).GetPayment(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceGetPaymentArgs() interface{} {
	return payment.NewPaymentServiceGetPaymentArgs()
}

func newPaymentServiceGetPaymentResult() interface{} {
	return payment.NewPaymentServiceGetPaymentResult()
}

func listPaymentsByOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceListPaymentsByOrderArgs)
	realResult := result.(*payment.PaymentServiceListPaymentsByOrderResult)
	success, err := handler.(payment.PaymentService).ListPaymentsByOrder(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceListPaymentsByOrderArgs() interface{} {
	return payment.NewPaymentServiceListPaymentsByOrderArgs()
}

func newPaymentServiceListPaymentsByOrderResult() interface{} {
	return payment.NewPaymentServiceListPaymentsByOrderResult()
}

func confirmPaymentSuccessHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*payment.PaymentServiceConfirmPaymentSuccessArgs)
	realResult := result.(*payment.PaymentServiceConfirmPaymentSuccessResult)
	success, err := handler.(payment.PaymentService).ConfirmPaymentSuccess(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPaymentServiceConfirmPaymentSuccessArgs() interface{} {
	return payment.NewPaymentServiceConfirmPaymentSuccessArgs()
}

func newPaymentServiceConfirmPaymentSuccessResult() interface{} {
	return payment.NewPaymentServiceConfirmPaymentSuccessResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreatePayment(ctx context.Context, request *payment.CreatePaymentRequest) (r *payment.CreatePaymentResponse, err error) {
	var _args payment.PaymentServiceCreatePaymentArgs
	_args.Request = request
	var _result payment.PaymentServiceCreatePaymentResult
	if err = p.c.Call(ctx, "createPayment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPayment(ctx context.Context, request *payment.GetPaymentRequest) (r *payment.GetPaymentResponse, err error) {
	var _args payment.PaymentServiceGetPaymentArgs
	_args.Request = request
	var _result payment.PaymentServiceGetPaymentResult
	if err = p.c.Call(ctx, "getPayment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListPaymentsByOrder(ctx context.Context, request *payment.ListPaymentsByOrderRequest) (r *payment.ListPaymentsByOrderResponse, err error) {
	var _args payment.PaymentServiceListPaymentsByOrderArgs
	_args.Request = request
	var _result payment.PaymentServiceListPaymentsByOrderResult
	if err = p.c.Call(ctx, "listPaymentsByOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmPaymentSuccess(ctx context.Context, request *payment.ConfirmPaymentSuccessRequest) (r *payment.ConfirmPaymentSuccessResponse, err error) {
	var _args payment.PaymentServiceConfirmPaymentSuccessArgs
	_args.Request = request
	var _result payment.PaymentServiceConfirmPaymentSuccessResult
	if err = p.c.Call(ctx, "confirmPaymentSuccess", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
