#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT_DIR"

export APP_ENV="${APP_ENV:-dev}"
export LOG_LEVEL="${LOG_LEVEL:-info}"
export LOG_DIR="${LOG_DIR:-logs}"
export OTEL_EXPORTER_OTLP_ENDPOINT="${OTEL_EXPORTER_OTLP_ENDPOINT:-localhost:4319}"
export INVENTORY_METRICS_ADDR="${INVENTORY_METRICS_ADDR:-:9095}"
export INVENTORY_SERVICE_CONFIG="${INVENTORY_SERVICE_CONFIG:-services/inventory-service/config/inventory-service.local.yaml}"
export INVENTORY_RPC_SERVICE="${INVENTORY_RPC_SERVICE:-meshcart.inventory}"
export INVENTORY_SERVICE_ADDR="${INVENTORY_SERVICE_ADDR:-127.0.0.1:8891}"
export INVENTORY_SERVICE_REGISTRY="${INVENTORY_SERVICE_REGISTRY:-consul}"
export CONSUL_ADDR="${CONSUL_ADDR:-127.0.0.1:8500}"
export INVENTORY_SERVICE_CONSUL_TCP_CHECK="${INVENTORY_SERVICE_CONSUL_TCP_CHECK:-false}"
export INVENTORY_SERVICE_SHUTDOWN_TIMEOUT_MS="${INVENTORY_SERVICE_SHUTDOWN_TIMEOUT_MS:-5000}"
export INVENTORY_SERVICE_PREFLIGHT_TIMEOUT_MS="${INVENTORY_SERVICE_PREFLIGHT_TIMEOUT_MS:-1500}"
export INVENTORY_SERVICE_DRAIN_TIMEOUT_MS="${INVENTORY_SERVICE_DRAIN_TIMEOUT_MS:-500}"

if [[ ! -f "$INVENTORY_SERVICE_CONFIG" ]]; then
  echo "[ERROR] config file not found: $INVENTORY_SERVICE_CONFIG" >&2
  exit 1
fi

echo "[INFO] starting inventory-service"
echo "[INFO] APP_ENV=$APP_ENV LOG_LEVEL=$LOG_LEVEL LOG_DIR=$LOG_DIR OTEL_EXPORTER_OTLP_ENDPOINT=$OTEL_EXPORTER_OTLP_ENDPOINT"
echo "[INFO] INVENTORY_METRICS_ADDR=$INVENTORY_METRICS_ADDR INVENTORY_SERVICE_CONFIG=$INVENTORY_SERVICE_CONFIG"
echo "[INFO] INVENTORY_RPC_SERVICE=$INVENTORY_RPC_SERVICE INVENTORY_SERVICE_ADDR=$INVENTORY_SERVICE_ADDR INVENTORY_SERVICE_REGISTRY=$INVENTORY_SERVICE_REGISTRY CONSUL_ADDR=$CONSUL_ADDR INVENTORY_SERVICE_CONSUL_TCP_CHECK=$INVENTORY_SERVICE_CONSUL_TCP_CHECK"
echo "[INFO] INVENTORY_SERVICE_SHUTDOWN_TIMEOUT_MS=$INVENTORY_SERVICE_SHUTDOWN_TIMEOUT_MS INVENTORY_SERVICE_PREFLIGHT_TIMEOUT_MS=$INVENTORY_SERVICE_PREFLIGHT_TIMEOUT_MS INVENTORY_SERVICE_DRAIN_TIMEOUT_MS=$INVENTORY_SERVICE_DRAIN_TIMEOUT_MS healthz=http://127.0.0.1${INVENTORY_METRICS_ADDR}/healthz readyz=http://127.0.0.1${INVENTORY_METRICS_ADDR}/readyz metrics=http://127.0.0.1${INVENTORY_METRICS_ADDR}/metrics"

exec go run ./services/inventory-service/rpc
