#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

export APP_ENV="${APP_ENV:-dev}"
export LOG_LEVEL="${LOG_LEVEL:-info}"
export LOG_DIR="${LOG_DIR:-logs}"
export OTEL_EXPORTER_OTLP_ENDPOINT="${OTEL_EXPORTER_OTLP_ENDPOINT:-localhost:4319}"
export GATEWAY_ADDR="${GATEWAY_ADDR:-:8080}"
export USER_RPC_SERVICE="${USER_RPC_SERVICE:-meshcart.user}"
export USER_RPC_ADDR="${USER_RPC_ADDR:-127.0.0.1:8888}"
export USER_RPC_DISCOVERY="${USER_RPC_DISCOVERY:-consul}"
export PRODUCT_RPC_SERVICE="${PRODUCT_RPC_SERVICE:-meshcart.product}"
export PRODUCT_RPC_ADDR="${PRODUCT_RPC_ADDR:-127.0.0.1:8889}"
export PRODUCT_RPC_DISCOVERY="${PRODUCT_RPC_DISCOVERY:-consul}"
export CONSUL_ADDR="${CONSUL_ADDR:-127.0.0.1:8500}"
export JWT_SECRET="${JWT_SECRET:-meshcart-dev-secret-change-me}"
export JWT_ISSUER="${JWT_ISSUER:-meshcart.gateway}"
export JWT_TIMEOUT_MINUTES="${JWT_TIMEOUT_MINUTES:-120}"
export JWT_MAX_REFRESH_MINUTES="${JWT_MAX_REFRESH_MINUTES:-720}"
export GATEWAY_SHUTDOWN_TIMEOUT_MS="${GATEWAY_SHUTDOWN_TIMEOUT_MS:-5000}"
export GATEWAY_PREFLIGHT_TIMEOUT_MS="${GATEWAY_PREFLIGHT_TIMEOUT_MS:-1500}"
export GATEWAY_DRAIN_TIMEOUT_MS="${GATEWAY_DRAIN_TIMEOUT_MS:-500}"

echo "[INFO] starting gateway"
echo "[INFO] APP_ENV=$APP_ENV LOG_LEVEL=$LOG_LEVEL LOG_DIR=$LOG_DIR OTEL_EXPORTER_OTLP_ENDPOINT=$OTEL_EXPORTER_OTLP_ENDPOINT"
echo "[INFO] GATEWAY_ADDR=$GATEWAY_ADDR USER_RPC_SERVICE=$USER_RPC_SERVICE USER_RPC_ADDR=$USER_RPC_ADDR USER_RPC_DISCOVERY=$USER_RPC_DISCOVERY"
echo "[INFO] PRODUCT_RPC_SERVICE=$PRODUCT_RPC_SERVICE PRODUCT_RPC_ADDR=$PRODUCT_RPC_ADDR PRODUCT_RPC_DISCOVERY=$PRODUCT_RPC_DISCOVERY CONSUL_ADDR=$CONSUL_ADDR"
echo "[INFO] JWT_ISSUER=$JWT_ISSUER JWT_TIMEOUT_MINUTES=$JWT_TIMEOUT_MINUTES JWT_MAX_REFRESH_MINUTES=$JWT_MAX_REFRESH_MINUTES"
echo "[INFO] GATEWAY_SHUTDOWN_TIMEOUT_MS=$GATEWAY_SHUTDOWN_TIMEOUT_MS GATEWAY_PREFLIGHT_TIMEOUT_MS=$GATEWAY_PREFLIGHT_TIMEOUT_MS GATEWAY_DRAIN_TIMEOUT_MS=$GATEWAY_DRAIN_TIMEOUT_MS healthz=http://127.0.0.1${GATEWAY_ADDR}/healthz readyz=http://127.0.0.1${GATEWAY_ADDR}/readyz"

exec go run ./gateway/cmd/gateway
