#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

export APP_ENV="${APP_ENV:-dev}"
export LOG_LEVEL="${LOG_LEVEL:-info}"
export LOG_DIR="${LOG_DIR:-logs}"
export OTEL_EXPORTER_OTLP_ENDPOINT="${OTEL_EXPORTER_OTLP_ENDPOINT:-localhost:4319}"
export GATEWAY_ADDR="${GATEWAY_ADDR:-:8080}"
export USER_RPC_SERVICE="${USER_RPC_SERVICE:-meshcart.user}"
export USER_RPC_ADDR="${USER_RPC_ADDR:-127.0.0.1:8888}"
export USER_RPC_DISCOVERY="${USER_RPC_DISCOVERY:-consul}"
export CONSUL_ADDR="${CONSUL_ADDR:-127.0.0.1:8500}"

echo "[INFO] starting gateway"
echo "[INFO] APP_ENV=$APP_ENV LOG_LEVEL=$LOG_LEVEL LOG_DIR=$LOG_DIR OTEL_EXPORTER_OTLP_ENDPOINT=$OTEL_EXPORTER_OTLP_ENDPOINT"
echo "[INFO] GATEWAY_ADDR=$GATEWAY_ADDR USER_RPC_SERVICE=$USER_RPC_SERVICE USER_RPC_ADDR=$USER_RPC_ADDR USER_RPC_DISCOVERY=$USER_RPC_DISCOVERY CONSUL_ADDR=$CONSUL_ADDR"

exec go run ./gateway/cmd/gateway
