// Code generated by Kitex v0.16.1. DO NOT EDIT.

package cartservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	cart "meshcart/kitex_gen/meshcart/cart"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"getCart": kitex.NewMethodInfo(
		getCartHandler,
		newCartServiceGetCartArgs,
		newCartServiceGetCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"addCartItem": kitex.NewMethodInfo(
		addCartItemHandler,
		newCartServiceAddCartItemArgs,
		newCartServiceAddCartItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"updateCartItem": kitex.NewMethodInfo(
		updateCartItemHandler,
		newCartServiceUpdateCartItemArgs,
		newCartServiceUpdateCartItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"removeCartItem": kitex.NewMethodInfo(
		removeCartItemHandler,
		newCartServiceRemoveCartItemArgs,
		newCartServiceRemoveCartItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"clearCart": kitex.NewMethodInfo(
		clearCartHandler,
		newCartServiceClearCartArgs,
		newCartServiceClearCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	cartServiceServiceInfo                = NewServiceInfo()
	cartServiceServiceInfoForClient       = NewServiceInfoForClient()
	cartServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return cartServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return cartServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return cartServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CartService"
	handlerType := (*cart.CartService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "cart",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceGetCartArgs)
	realResult := result.(*cart.CartServiceGetCartResult)
	success, err := handler.(cart.CartService).GetCart(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceGetCartArgs() interface{} {
	return cart.NewCartServiceGetCartArgs()
}

func newCartServiceGetCartResult() interface{} {
	return cart.NewCartServiceGetCartResult()
}

func addCartItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceAddCartItemArgs)
	realResult := result.(*cart.CartServiceAddCartItemResult)
	success, err := handler.(cart.CartService).AddCartItem(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceAddCartItemArgs() interface{} {
	return cart.NewCartServiceAddCartItemArgs()
}

func newCartServiceAddCartItemResult() interface{} {
	return cart.NewCartServiceAddCartItemResult()
}

func updateCartItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceUpdateCartItemArgs)
	realResult := result.(*cart.CartServiceUpdateCartItemResult)
	success, err := handler.(cart.CartService).UpdateCartItem(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceUpdateCartItemArgs() interface{} {
	return cart.NewCartServiceUpdateCartItemArgs()
}

func newCartServiceUpdateCartItemResult() interface{} {
	return cart.NewCartServiceUpdateCartItemResult()
}

func removeCartItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceRemoveCartItemArgs)
	realResult := result.(*cart.CartServiceRemoveCartItemResult)
	success, err := handler.(cart.CartService).RemoveCartItem(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceRemoveCartItemArgs() interface{} {
	return cart.NewCartServiceRemoveCartItemArgs()
}

func newCartServiceRemoveCartItemResult() interface{} {
	return cart.NewCartServiceRemoveCartItemResult()
}

func clearCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cart.CartServiceClearCartArgs)
	realResult := result.(*cart.CartServiceClearCartResult)
	success, err := handler.(cart.CartService).ClearCart(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCartServiceClearCartArgs() interface{} {
	return cart.NewCartServiceClearCartArgs()
}

func newCartServiceClearCartResult() interface{} {
	return cart.NewCartServiceClearCartResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetCart(ctx context.Context, request *cart.GetCartRequest) (r *cart.GetCartResponse, err error) {
	var _args cart.CartServiceGetCartArgs
	_args.Request = request
	var _result cart.CartServiceGetCartResult
	if err = p.c.Call(ctx, "getCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddCartItem(ctx context.Context, request *cart.AddCartItemRequest) (r *cart.AddCartItemResponse, err error) {
	var _args cart.CartServiceAddCartItemArgs
	_args.Request = request
	var _result cart.CartServiceAddCartItemResult
	if err = p.c.Call(ctx, "addCartItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateCartItem(ctx context.Context, request *cart.UpdateCartItemRequest) (r *cart.UpdateCartItemResponse, err error) {
	var _args cart.CartServiceUpdateCartItemArgs
	_args.Request = request
	var _result cart.CartServiceUpdateCartItemResult
	if err = p.c.Call(ctx, "updateCartItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveCartItem(ctx context.Context, request *cart.RemoveCartItemRequest) (r *cart.RemoveCartItemResponse, err error) {
	var _args cart.CartServiceRemoveCartItemArgs
	_args.Request = request
	var _result cart.CartServiceRemoveCartItemResult
	if err = p.c.Call(ctx, "removeCartItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ClearCart(ctx context.Context, request *cart.ClearCartRequest) (r *cart.ClearCartResponse, err error) {
	var _args cart.CartServiceClearCartArgs
	_args.Request = request
	var _result cart.CartServiceClearCartResult
	if err = p.c.Call(ctx, "clearCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
