// Code generated by Kitex v0.16.1. DO NOT EDIT.

package cartservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	cart "meshcart/kitex_gen/meshcart/cart"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetCart(ctx context.Context, request *cart.GetCartRequest, callOptions ...callopt.Option) (r *cart.GetCartResponse, err error)
	AddCartItem(ctx context.Context, request *cart.AddCartItemRequest, callOptions ...callopt.Option) (r *cart.AddCartItemResponse, err error)
	UpdateCartItem(ctx context.Context, request *cart.UpdateCartItemRequest, callOptions ...callopt.Option) (r *cart.UpdateCartItemResponse, err error)
	RemoveCartItem(ctx context.Context, request *cart.RemoveCartItemRequest, callOptions ...callopt.Option) (r *cart.RemoveCartItemResponse, err error)
	ClearCart(ctx context.Context, request *cart.ClearCartRequest, callOptions ...callopt.Option) (r *cart.ClearCartResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCartServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCartServiceClient struct {
	*kClient
}

func (p *kCartServiceClient) GetCart(ctx context.Context, request *cart.GetCartRequest, callOptions ...callopt.Option) (r *cart.GetCartResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCart(ctx, request)
}

func (p *kCartServiceClient) AddCartItem(ctx context.Context, request *cart.AddCartItemRequest, callOptions ...callopt.Option) (r *cart.AddCartItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddCartItem(ctx, request)
}

func (p *kCartServiceClient) UpdateCartItem(ctx context.Context, request *cart.UpdateCartItemRequest, callOptions ...callopt.Option) (r *cart.UpdateCartItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateCartItem(ctx, request)
}

func (p *kCartServiceClient) RemoveCartItem(ctx context.Context, request *cart.RemoveCartItemRequest, callOptions ...callopt.Option) (r *cart.RemoveCartItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveCartItem(ctx, request)
}

func (p *kCartServiceClient) ClearCart(ctx context.Context, request *cart.ClearCartRequest, callOptions ...callopt.Option) (r *cart.ClearCartResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ClearCart(ctx, request)
}
