CREATE TABLE IF NOT EXISTS `product_sku_attrs` (
  `id` BIGINT NOT NULL,
  `sku_id` BIGINT NOT NULL,
  `attr_name` VARCHAR(64) NOT NULL,
  `attr_value` VARCHAR(128) NOT NULL,
  `sort` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
