#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT_DIR"

export APP_ENV="${APP_ENV:-dev}"
export LOG_LEVEL="${LOG_LEVEL:-info}"
export LOG_DIR="${LOG_DIR:-logs}"
export OTEL_EXPORTER_OTLP_ENDPOINT="${OTEL_EXPORTER_OTLP_ENDPOINT:-localhost:4319}"
export PRODUCT_METRICS_ADDR="${PRODUCT_METRICS_ADDR:-:9093}"
export PRODUCT_SERVICE_CONFIG="${PRODUCT_SERVICE_CONFIG:-services/product-service/config/product-service.local.yaml}"
export PRODUCT_SERVICE_CONFIG_SOURCE="${PRODUCT_SERVICE_CONFIG_SOURCE:-file}"
export PRODUCT_RPC_SERVICE="${PRODUCT_RPC_SERVICE:-meshcart.product}"
export PRODUCT_SERVICE_ADDR="${PRODUCT_SERVICE_ADDR:-127.0.0.1:8889}"
export PRODUCT_SERVICE_REGISTRY="${PRODUCT_SERVICE_REGISTRY:-consul}"
export CONSUL_ADDR="${CONSUL_ADDR:-127.0.0.1:8500}"
export PRODUCT_SERVICE_CONSUL_TCP_CHECK="${PRODUCT_SERVICE_CONSUL_TCP_CHECK:-false}"
export PRODUCT_SERVICE_SHUTDOWN_TIMEOUT_MS="${PRODUCT_SERVICE_SHUTDOWN_TIMEOUT_MS:-5000}"

if [[ ! -f "$PRODUCT_SERVICE_CONFIG" ]]; then
  echo "[ERROR] config file not found: $PRODUCT_SERVICE_CONFIG" >&2
  exit 1
fi

echo "[INFO] starting product-service"
echo "[INFO] APP_ENV=$APP_ENV LOG_LEVEL=$LOG_LEVEL LOG_DIR=$LOG_DIR OTEL_EXPORTER_OTLP_ENDPOINT=$OTEL_EXPORTER_OTLP_ENDPOINT"
echo "[INFO] PRODUCT_METRICS_ADDR=$PRODUCT_METRICS_ADDR PRODUCT_SERVICE_CONFIG=$PRODUCT_SERVICE_CONFIG PRODUCT_SERVICE_CONFIG_SOURCE=$PRODUCT_SERVICE_CONFIG_SOURCE"
echo "[INFO] PRODUCT_RPC_SERVICE=$PRODUCT_RPC_SERVICE PRODUCT_SERVICE_ADDR=$PRODUCT_SERVICE_ADDR PRODUCT_SERVICE_REGISTRY=$PRODUCT_SERVICE_REGISTRY CONSUL_ADDR=$CONSUL_ADDR PRODUCT_SERVICE_CONSUL_TCP_CHECK=$PRODUCT_SERVICE_CONSUL_TCP_CHECK"
echo "[INFO] PRODUCT_SERVICE_SHUTDOWN_TIMEOUT_MS=$PRODUCT_SERVICE_SHUTDOWN_TIMEOUT_MS healthz=http://127.0.0.1${PRODUCT_METRICS_ADDR}/healthz readyz=http://127.0.0.1${PRODUCT_METRICS_ADDR}/readyz metrics=http://127.0.0.1${PRODUCT_METRICS_ADDR}/metrics"

exec go run ./services/product-service/rpc
