server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service
      - replacement: meshcart
        target_label: project
  - job_name: meshcart-local-files
    static_configs:
      - targets:
          - localhost
        labels:
          job: meshcart-local-files
          project: meshcart
          source: file
          service: gateway
          __path__: /workspace/logs/gateway.log
      - targets:
          - localhost
        labels:
          job: meshcart-local-files
          project: meshcart
          source: file
          service: user-service
          __path__: /workspace/logs/user-service.log
      - targets:
          - localhost
        labels:
          job: meshcart-local-files
          project: meshcart
          source: file
          service: product-service
          __path__: /workspace/logs/product-service.log
      - targets:
          - localhost
        labels:
          job: meshcart-local-files
          project: meshcart
          source: file
          service: cart-service
          __path__: /workspace/logs/cart-service.log
      - targets:
          - localhost
        labels:
          job: meshcart-local-files
          project: meshcart
          source: file
          service: inventory-service
          __path__: /workspace/logs/inventory-service.log
