// Code generated by Kitex v0.16.1. DO NOT EDIT.

package inventoryservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	inventory "meshcart/kitex_gen/meshcart/inventory"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetSkuStock(ctx context.Context, request *inventory.GetSkuStockRequest, callOptions ...callopt.Option) (r *inventory.GetSkuStockResponse, err error)
	BatchGetSkuStock(ctx context.Context, request *inventory.BatchGetSkuStockRequest, callOptions ...callopt.Option) (r *inventory.BatchGetSkuStockResponse, err error)
	CheckSaleableStock(ctx context.Context, request *inventory.CheckSaleableStockRequest, callOptions ...callopt.Option) (r *inventory.CheckSaleableStockResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kInventoryServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInventoryServiceClient struct {
	*kClient
}

func (p *kInventoryServiceClient) GetSkuStock(ctx context.Context, request *inventory.GetSkuStockRequest, callOptions ...callopt.Option) (r *inventory.GetSkuStockResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSkuStock(ctx, request)
}

func (p *kInventoryServiceClient) BatchGetSkuStock(ctx context.Context, request *inventory.BatchGetSkuStockRequest, callOptions ...callopt.Option) (r *inventory.BatchGetSkuStockResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetSkuStock(ctx, request)
}

func (p *kInventoryServiceClient) CheckSaleableStock(ctx context.Context, request *inventory.CheckSaleableStockRequest, callOptions ...callopt.Option) (r *inventory.CheckSaleableStockResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckSaleableStock(ctx, request)
}
