// Code generated by Kitex v0.16.1. DO NOT EDIT.

package inventoryservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	inventory "meshcart/kitex_gen/meshcart/inventory"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"getSkuStock": kitex.NewMethodInfo(
		getSkuStockHandler,
		newInventoryServiceGetSkuStockArgs,
		newInventoryServiceGetSkuStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"batchGetSkuStock": kitex.NewMethodInfo(
		batchGetSkuStockHandler,
		newInventoryServiceBatchGetSkuStockArgs,
		newInventoryServiceBatchGetSkuStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"checkSaleableStock": kitex.NewMethodInfo(
		checkSaleableStockHandler,
		newInventoryServiceCheckSaleableStockArgs,
		newInventoryServiceCheckSaleableStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"initSkuStocks": kitex.NewMethodInfo(
		initSkuStocksHandler,
		newInventoryServiceInitSkuStocksArgs,
		newInventoryServiceInitSkuStocksResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"initSkuStocksSaga": kitex.NewMethodInfo(
		initSkuStocksSagaHandler,
		newInventoryServiceInitSkuStocksSagaArgs,
		newInventoryServiceInitSkuStocksSagaResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"compensateInitSkuStocksSaga": kitex.NewMethodInfo(
		compensateInitSkuStocksSagaHandler,
		newInventoryServiceCompensateInitSkuStocksSagaArgs,
		newInventoryServiceCompensateInitSkuStocksSagaResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"freezeSkuStocks": kitex.NewMethodInfo(
		freezeSkuStocksHandler,
		newInventoryServiceFreezeSkuStocksArgs,
		newInventoryServiceFreezeSkuStocksResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"adjustStock": kitex.NewMethodInfo(
		adjustStockHandler,
		newInventoryServiceAdjustStockArgs,
		newInventoryServiceAdjustStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"reserveSkuStocks": kitex.NewMethodInfo(
		reserveSkuStocksHandler,
		newInventoryServiceReserveSkuStocksArgs,
		newInventoryServiceReserveSkuStocksResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"releaseReservedSkuStocks": kitex.NewMethodInfo(
		releaseReservedSkuStocksHandler,
		newInventoryServiceReleaseReservedSkuStocksArgs,
		newInventoryServiceReleaseReservedSkuStocksResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"confirmDeductReservedSkuStocks": kitex.NewMethodInfo(
		confirmDeductReservedSkuStocksHandler,
		newInventoryServiceConfirmDeductReservedSkuStocksArgs,
		newInventoryServiceConfirmDeductReservedSkuStocksResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	inventoryServiceServiceInfo                = NewServiceInfo()
	inventoryServiceServiceInfoForClient       = NewServiceInfoForClient()
	inventoryServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return inventoryServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return inventoryServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return inventoryServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InventoryService"
	handlerType := (*inventory.InventoryService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "inventory",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getSkuStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceGetSkuStockArgs)
	realResult := result.(*inventory.InventoryServiceGetSkuStockResult)
	success, err := handler.(inventory.InventoryService).GetSkuStock(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceGetSkuStockArgs() interface{} {
	return inventory.NewInventoryServiceGetSkuStockArgs()
}

func newInventoryServiceGetSkuStockResult() interface{} {
	return inventory.NewInventoryServiceGetSkuStockResult()
}

func batchGetSkuStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceBatchGetSkuStockArgs)
	realResult := result.(*inventory.InventoryServiceBatchGetSkuStockResult)
	success, err := handler.(inventory.InventoryService).BatchGetSkuStock(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceBatchGetSkuStockArgs() interface{} {
	return inventory.NewInventoryServiceBatchGetSkuStockArgs()
}

func newInventoryServiceBatchGetSkuStockResult() interface{} {
	return inventory.NewInventoryServiceBatchGetSkuStockResult()
}

func checkSaleableStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceCheckSaleableStockArgs)
	realResult := result.(*inventory.InventoryServiceCheckSaleableStockResult)
	success, err := handler.(inventory.InventoryService).CheckSaleableStock(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceCheckSaleableStockArgs() interface{} {
	return inventory.NewInventoryServiceCheckSaleableStockArgs()
}

func newInventoryServiceCheckSaleableStockResult() interface{} {
	return inventory.NewInventoryServiceCheckSaleableStockResult()
}

func initSkuStocksHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceInitSkuStocksArgs)
	realResult := result.(*inventory.InventoryServiceInitSkuStocksResult)
	success, err := handler.(inventory.InventoryService).InitSkuStocks(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceInitSkuStocksArgs() interface{} {
	return inventory.NewInventoryServiceInitSkuStocksArgs()
}

func newInventoryServiceInitSkuStocksResult() interface{} {
	return inventory.NewInventoryServiceInitSkuStocksResult()
}

func initSkuStocksSagaHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceInitSkuStocksSagaArgs)
	realResult := result.(*inventory.InventoryServiceInitSkuStocksSagaResult)
	success, err := handler.(inventory.InventoryService).InitSkuStocksSaga(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceInitSkuStocksSagaArgs() interface{} {
	return inventory.NewInventoryServiceInitSkuStocksSagaArgs()
}

func newInventoryServiceInitSkuStocksSagaResult() interface{} {
	return inventory.NewInventoryServiceInitSkuStocksSagaResult()
}

func compensateInitSkuStocksSagaHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceCompensateInitSkuStocksSagaArgs)
	realResult := result.(*inventory.InventoryServiceCompensateInitSkuStocksSagaResult)
	success, err := handler.(inventory.InventoryService).CompensateInitSkuStocksSaga(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceCompensateInitSkuStocksSagaArgs() interface{} {
	return inventory.NewInventoryServiceCompensateInitSkuStocksSagaArgs()
}

func newInventoryServiceCompensateInitSkuStocksSagaResult() interface{} {
	return inventory.NewInventoryServiceCompensateInitSkuStocksSagaResult()
}

func freezeSkuStocksHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceFreezeSkuStocksArgs)
	realResult := result.(*inventory.InventoryServiceFreezeSkuStocksResult)
	success, err := handler.(inventory.InventoryService).FreezeSkuStocks(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceFreezeSkuStocksArgs() interface{} {
	return inventory.NewInventoryServiceFreezeSkuStocksArgs()
}

func newInventoryServiceFreezeSkuStocksResult() interface{} {
	return inventory.NewInventoryServiceFreezeSkuStocksResult()
}

func adjustStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceAdjustStockArgs)
	realResult := result.(*inventory.InventoryServiceAdjustStockResult)
	success, err := handler.(inventory.InventoryService).AdjustStock(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceAdjustStockArgs() interface{} {
	return inventory.NewInventoryServiceAdjustStockArgs()
}

func newInventoryServiceAdjustStockResult() interface{} {
	return inventory.NewInventoryServiceAdjustStockResult()
}

func reserveSkuStocksHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceReserveSkuStocksArgs)
	realResult := result.(*inventory.InventoryServiceReserveSkuStocksResult)
	success, err := handler.(inventory.InventoryService).ReserveSkuStocks(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceReserveSkuStocksArgs() interface{} {
	return inventory.NewInventoryServiceReserveSkuStocksArgs()
}

func newInventoryServiceReserveSkuStocksResult() interface{} {
	return inventory.NewInventoryServiceReserveSkuStocksResult()
}

func releaseReservedSkuStocksHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceReleaseReservedSkuStocksArgs)
	realResult := result.(*inventory.InventoryServiceReleaseReservedSkuStocksResult)
	success, err := handler.(inventory.InventoryService).ReleaseReservedSkuStocks(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceReleaseReservedSkuStocksArgs() interface{} {
	return inventory.NewInventoryServiceReleaseReservedSkuStocksArgs()
}

func newInventoryServiceReleaseReservedSkuStocksResult() interface{} {
	return inventory.NewInventoryServiceReleaseReservedSkuStocksResult()
}

func confirmDeductReservedSkuStocksHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceConfirmDeductReservedSkuStocksArgs)
	realResult := result.(*inventory.InventoryServiceConfirmDeductReservedSkuStocksResult)
	success, err := handler.(inventory.InventoryService).ConfirmDeductReservedSkuStocks(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInventoryServiceConfirmDeductReservedSkuStocksArgs() interface{} {
	return inventory.NewInventoryServiceConfirmDeductReservedSkuStocksArgs()
}

func newInventoryServiceConfirmDeductReservedSkuStocksResult() interface{} {
	return inventory.NewInventoryServiceConfirmDeductReservedSkuStocksResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetSkuStock(ctx context.Context, request *inventory.GetSkuStockRequest) (r *inventory.GetSkuStockResponse, err error) {
	var _args inventory.InventoryServiceGetSkuStockArgs
	_args.Request = request
	var _result inventory.InventoryServiceGetSkuStockResult
	if err = p.c.Call(ctx, "getSkuStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetSkuStock(ctx context.Context, request *inventory.BatchGetSkuStockRequest) (r *inventory.BatchGetSkuStockResponse, err error) {
	var _args inventory.InventoryServiceBatchGetSkuStockArgs
	_args.Request = request
	var _result inventory.InventoryServiceBatchGetSkuStockResult
	if err = p.c.Call(ctx, "batchGetSkuStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckSaleableStock(ctx context.Context, request *inventory.CheckSaleableStockRequest) (r *inventory.CheckSaleableStockResponse, err error) {
	var _args inventory.InventoryServiceCheckSaleableStockArgs
	_args.Request = request
	var _result inventory.InventoryServiceCheckSaleableStockResult
	if err = p.c.Call(ctx, "checkSaleableStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InitSkuStocks(ctx context.Context, request *inventory.InitSkuStocksRequest) (r *inventory.InitSkuStocksResponse, err error) {
	var _args inventory.InventoryServiceInitSkuStocksArgs
	_args.Request = request
	var _result inventory.InventoryServiceInitSkuStocksResult
	if err = p.c.Call(ctx, "initSkuStocks", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InitSkuStocksSaga(ctx context.Context, request *inventory.InitSkuStocksSagaRequest) (r *inventory.InitSkuStocksResponse, err error) {
	var _args inventory.InventoryServiceInitSkuStocksSagaArgs
	_args.Request = request
	var _result inventory.InventoryServiceInitSkuStocksSagaResult
	if err = p.c.Call(ctx, "initSkuStocksSaga", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CompensateInitSkuStocksSaga(ctx context.Context, request *inventory.CompensateInitSkuStocksSagaRequest) (r *inventory.CompensateInitSkuStocksSagaResponse, err error) {
	var _args inventory.InventoryServiceCompensateInitSkuStocksSagaArgs
	_args.Request = request
	var _result inventory.InventoryServiceCompensateInitSkuStocksSagaResult
	if err = p.c.Call(ctx, "compensateInitSkuStocksSaga", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FreezeSkuStocks(ctx context.Context, request *inventory.FreezeSkuStocksRequest) (r *inventory.FreezeSkuStocksResponse, err error) {
	var _args inventory.InventoryServiceFreezeSkuStocksArgs
	_args.Request = request
	var _result inventory.InventoryServiceFreezeSkuStocksResult
	if err = p.c.Call(ctx, "freezeSkuStocks", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdjustStock(ctx context.Context, request *inventory.AdjustStockRequest) (r *inventory.AdjustStockResponse, err error) {
	var _args inventory.InventoryServiceAdjustStockArgs
	_args.Request = request
	var _result inventory.InventoryServiceAdjustStockResult
	if err = p.c.Call(ctx, "adjustStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReserveSkuStocks(ctx context.Context, request *inventory.ReserveSkuStocksRequest) (r *inventory.ReserveSkuStocksResponse, err error) {
	var _args inventory.InventoryServiceReserveSkuStocksArgs
	_args.Request = request
	var _result inventory.InventoryServiceReserveSkuStocksResult
	if err = p.c.Call(ctx, "reserveSkuStocks", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReleaseReservedSkuStocks(ctx context.Context, request *inventory.ReleaseReservedSkuStocksRequest) (r *inventory.ReleaseReservedSkuStocksResponse, err error) {
	var _args inventory.InventoryServiceReleaseReservedSkuStocksArgs
	_args.Request = request
	var _result inventory.InventoryServiceReleaseReservedSkuStocksResult
	if err = p.c.Call(ctx, "releaseReservedSkuStocks", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmDeductReservedSkuStocks(ctx context.Context, request *inventory.ConfirmDeductReservedSkuStocksRequest) (r *inventory.ConfirmDeductReservedSkuStocksResponse, err error) {
	var _args inventory.InventoryServiceConfirmDeductReservedSkuStocksArgs
	_args.Request = request
	var _result inventory.InventoryServiceConfirmDeductReservedSkuStocksResult
	if err = p.c.Call(ctx, "confirmDeductReservedSkuStocks", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
